### ISSUE TITLE
Calculation of "Grundwerte" uses base attribute values only

### ISSUE THREAD

**Issue by YuanRamirez** [kreuvf/roll20-character-sheets#1]
Lifepoints, Stamina and Astral Energy are calculated with base attributes only (should be base + modifiers)

**Comment by kreuvf** [comment]
(If I should write in English, please say so.)

Ich denke, dass das Problem hier ist, dass der Heldenbogen als Modifikator nicht den Modifikator aus der Generierung meint, sondern temporäre Veränderungen durch einen Attributo oder Krankheiten/Gifte. Die Grundwerte werden in solchen Fällen nämlich nicht neu ausgerechnet - AT/PA/FK-Basiswerte jedoch schon, weshalb das bei diesen so eingebaut ist.

Hinweis: Der Bogen ist größtenteils nicht von mir, ich habe ihn nur entdeckt und versuche ihn so gut es geht zu verbessern. Das von dir beschriebene Problem bestand schon vor meinen Änderungen, weshalb ich mir nicht absolut sicher sein kann, dass meine Interpretation stimmt.

Eine Lösung für dieses Problem sollte aber schnell gefunden sein: Entweder eine bessere Benennung der Spalten (inkl. Ausfüllhinweisen) oder Hinzufügen eines zusätzlichen Tabs für die Werte aus der Generierung (mein Favorit ^.^). Durch einen solchen Tab könnte das Character Sheet auch erkennen, wenn eine Eigenschaft über den Maximalwert hinaus geändert werden soll.

**Comment by YuanRamirez** [comment]
Ah, achso! Dann hab ich das einfach nicht richtig gecheckt ^^'
Klingt aber soweit ganz gut. Ein zusätzlicher Tab ist vermutlich deutlich mehr Arbeit, oder nicht? Ich meine, wenn das nicht zu viele Umstände sind, ist es die Mehr-Arbeit wahrscheinlich wert, einfach um auch in Zukunft weitere Nachfragen wie die meine zu verhindern :D

**Comment by kreuvf** [comment]
Ein zusätzlicher Tab ist nicht viel Arbeit. Die Schwierigkeit wird nur darin bestehen dieses neue Feature so einzubauen, dass es automatisch mit den Daten aus alten Bögen funktioniert. Übrigens: Dass du das nicht richtig gecheckt hast, mag vielleicht zutreffen, ist aber ein Zeichen für schlechtes Design des Benutzerinterfaces. ^^ Aufgrund mangelnder Dokumentation ist auch meine Interpretation nicht mehr als bloßes Raten.

**Comment by kreuvf** [comment]
So, habe nochmal die Regelwerke abgesucht und auch mit meinem Meister Rücksprache gehalten: Die Grundwerte berechnen sich nicht neu, wenn sich Eigenschaften temporär verändern. Nicht umsonst steht bei Wunden dazu, wenn sich AT/PA verändern.

Daher werde ich das so umbauen, dass auch MR, INI, AT, PA und FK sich nicht mehr auf Basis temporärer Veränderungen verändern. Ich überlege aber noch, ob es tatsächlich ein eigenes Generierungstab braucht ;D

**Comment by Markus1204** [comment]
Ich schreib das hier mal rein weil es hier auch um die Grundwerte geht... Manchmal - und mir will nicht in den Kopf warum das so ist - passiert folgendes:

Ich trag die Grundwerte in den Sheet ein indem ich ganz normal die Basis verändere, denn Modis sind nur für temporäre Mali / Boni etc. gedacht... Die Werte werden auch erstmal übernommen und alles ist richtig.

Wenn ich dann aber während einer anderen Sitzung den Sheet öffne kann es sein, dass zwar die veränderten Basis Werte noch stimmen, aber die Endwerte (Basis + Mod) einfach mal ein paar Punkte darunter liegen... Es sind KEINE Modifikatoren eingetragen und auch die Basis wurde nicht weiter verändert...

Das einzige was bisher geholfen hat war den besagten Sheet zu löschen und für diesen Charakter einen neuen Sheet anzulegen inklusive dem erneuten Übertragen... Es kommt zwar nur ab und an vor, allerdings hab ich keine Ahnung was diesen Bug auslöst...

**Comment by kreuvf** [comment]
Solange ich den Bug nicht selbst reproduzieren kann, kann ich ihn leider auch nicht beheben. Wenn du das reproduzieren kannst (und nur dann :P), verdient der Bug ein eigenes Issue. Sollte ich dieses Issue also schließen, bedeutet das nicht automatisch auch, dass dein Bug behoben ist ^.^
