### ISSUE TITLE
Das Feld PA_Aktiv wird nicht gesetzt

### ISSUE THREAD

**Issue by nurmatthias** [kreuvf/roll20-character-sheets#100]
Hallo,

das Feld PA_Aktiv wird nicht angelegt/aktualisiert. Dadurch können im Sheet Kampf -> Nahkampf die Würfel für Paraden nicht benutzt werden.
Das Feld kann manuell angelegt werden, dann funktioniert es.

Im Sheet Kampf -> Ausrüstung werden zusätzlich die Werte für Paraden bei den Waffen nicht korrekt berechnet. Hier wird der Talentwert und die Verteilung ignoriert, Attacke wird soweit korrekt berechnet.

**Comment by kreuvf** [comment]
> das Feld PA_Aktiv wird nicht angelegt/aktualisiert. Dadurch können im Sheet Kampf -> Nahkampf die Würfel für Paraden nicht benutzt werden. Das Feld kann manuell angelegt werden, dann funktioniert es.

Klingt nach #91. Abhilfe schafft in der Regel bestimmte Dinge im Charakterbogen zu tun. Einmal eine Wunde ein- und wieder austragen. Nicht manuell anlegen, `PA_Aktiv` wird gesetzt, wenn `calculateCombatValues()` aufgerufen wird und korrekt durchläuft. Gegebenenfalls Debug-Modus einschalten und Konsolenausgabe beobachten und nach Meldungen dieser Funktion Ausschau halten. Ich kann dabei auch helfen, falls nötig.

> Im Sheet Kampf -> Ausrüstung werden zusätzlich die Werte für Paraden bei den Waffen nicht korrekt berechnet. Hier wird der Talentwert und die Verteilung ignoriert, Attacke wird soweit korrekt berechnet.

Die Verteilung muss händisch mit den Basiswerten verrechnet werden (Problem ist bekannt, s. #53).

Paar Fragen habe ich noch:
* Ist eine Waffe aktiv?
* Welche Kampftechnik wird für AT/PA verwendet?
* Sind alle Werte der gewählten Waffe ausgefüllt und "sinnvoll"?
* Sind die Werte für AT/PA der gewählten Kampftechniken unter Talente > Kampftechniken eingestellt?
* Sind Schilde beteiligt?

**Comment by nurmatthias** [comment]
Hallo,
danke für die schnelle Antwort :)
Das Problem saß vor dem Bildschirm, ich mach dann hier mal zu

**Comment by kreuvf** [comment]
> Hallo, danke für die schnelle Antwort :)

Kein Problem :D

> Das Problem saß vor dem Bildschirm, ich mach dann hier mal zu

Möchtest du mir noch verraten, was genau das Problem war? Der Charakterbogen könnte immer noch in puncto Bedienerfreundlichkeit verbessert werden und solche Beschreibungen sind für mich hilfreich. :)

**Comment by nurmatthias** [comment]
Hallo,

entschuldige die späte Antwort, war über das WE etwas beschäftigt.


Ich hatte vergessen hier die Waffentalente noch einmal zu setzen:



Ist also eigentlich logisch.

Danke für deine Mühen!


Viele Grüße
Matthias


Von: Kreuvf
Gesendet: Freitag, 28. Januar 2022 21:59
An: kreuvf/roll20-character-sheets
Cc: Matthias; State change
Betreff: Re: [kreuvf/roll20-character-sheets] Das Feld PA_Aktiv wird nichtgesetzt (Issue #100)

Hallo, danke für die schnelle Antwort :)
Kein Problem :D
Das Problem saß vor dem Bildschirm, ich mach dann hier mal zu
Möchtest du mir noch verraten, was genau das Problem war? Der Charakterbogen könnte immer noch in puncto Bedienerfreundlichkeit verbessert werden und solche Beschreibungen sind für mich hilfreich. :)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
