### ISSUE TITLE
Neu erstellte Charaktere können nicht würfeln.

### ISSUE THREAD

**Issue by Baguron** [kreuvf/roll20-character-sheets#105]
Moin.

Habe heute einen Charakter erstellt und vollständig eingetragen, bekomme aber nun wenn ich bspw. Fährtensuchen würfeln will folgende Fehler: 
No attribute was found for @{Valpo Moritatio|cs_talent}
No attribute was found for @{Valpo Moritatio|cf_talent}
No attribute was found for @{Valpo Moritatio|cs_talent}
No attribute was found for @{Valpo Moritatio|cf_talent}
Eigenschaften und Talentwerte sind aber alle normal eingetragen.

**Comment by kreuvf** [comment]
Lässt sich beheben, indem du einmal z. B. Tollpatsch ein- und wieder ausschaltest. Sag mir, ob das geholfen hat.

Mein Gefühl, dass ich was vergessen hatte, war also richtig: Bei neuen Charakteren werden die Grenzen für 1/20 nicht gesetzt. ;)

Da das mit einer vernünftigen Initialisierung (Issue #91) behebbar ist, setze ich dieses Issue mal als Duplikat davon.

**Comment by Baguron** [comment]
Jo das hat geholfen
