### ISSUE TITLE
Zauberliste verschoben

### ISSUE THREAD

**Issue by bornaqua** [kreuvf/roll20-character-sheets#107]
Hi,
einige Buttons in der Zauberliste würfeln den falschen Zauber. ( -> = würfelt )
Kraft des Erzes    -> Krähenruf
Kraft des Humus -> Kraft des Erzes
Krähenruf            -> Kraft des Humus

**Comment by kreuvf** [comment]
Wow, das ist echt ein dummer Fehler xD

**Comment by kreuvf** [comment]
Scheinen aber die einzigen drei Zauber zu sein, die betroffen sind. Immerhin ^.^ Danke für's Melden.

**Comment by kreuvf** [comment]
Wenn der Pull Request akzeptiert wird, dann ist das auch korrigiert. :)

**Comment by kreuvf** [comment]
Wurde aus mir unbekannten Gründen nicht automatisch geschlossen.
