### ISSUE TITLE
Myranor Zauber

### ISSUE THREAD

**Issue by SauronAnnatar** [kreuvf/roll20-character-sheets#110]
Gäbe es vielleicht die Möglichkeit, nicht nur die Zauber aus den Dunklen Zeiten hinzuzufügen, sondern auch die Quellen aus Myranor? Das wäre echt Klasse und im Gegensatz zu den Zaubern aus DSA hält sich das ja sogar in Grenzen.

**Comment by kreuvf** [comment]
Dazu kann ich leider nichts sagen, da ich kein einziges Quellenbuch zu Myranor habe. Vielleicht magst du mir kurz umreißen, wie die Magie in Myranor funktioniert?

**Comment by Rondragos** [comment]
Ich habe gerade ein bisschen angefangen, das zu machen. Bin nach längerer Pause wieder dabei zu coden und fuchse mich gerade wieder rein.
Meine Idee ist gerade, ein "Myranor-Update" zu machen, das (ausblendbar) eben die Zauber hinzufügt, sowie die handvoll zusätzlicher Talente und eventuell auch die Sprachen.
Es soll erstmal sehr basic werden, soweit ich weiß hat kreuvf eh noch vor die Magieseite mal zu überarbeiten um irgendwie auch die Möglichkeit einzubauen, denselben Zauber in verschiedenen Repräsentationen einzubauen. Größere Modifikationen würde ich wohl frühestens danach angehen.
@kreuvf Zur Magie: Es gibt in Myranor einige Zauber (je 1 bis 2 zu jeder "Quelle", also mit ca. 30-40 Quellen überschaubar), die aber nur ein gewisses "Grundgerüst" bilden um entweder mithilfe von "Spontanzauberei-SF" einen Effekt zu improvisieren oder (viel häufiger), eine bestimmte Formel (die die Randbedingungen wie Zauber- und Wirkungsdauer, Reichweite, Ziel und konkreten Effekt enthält) damit zu sprechen. Regeltechnisch hat man zum Zauber einen ZfW und eine entsprechende Probe, die immer um die "Anrufungsschwierigkeit" der Formel (oder des Effekts) erschwert ist und dann bei Formeln um die bekannte Qualität (1-7 ähnlich wie wahre Namen bei der aventurischen Beschwörung) erleichtert wird. Kompliziert wird es erst mit der Optionalregel sich die Zauber selbst zusammenzustellen (deren Fokus zu erweitern oder einzuschränken, etc.). Aber ich glaube das würde erstmal den Rahmen sprengen.

**Comment by kreuvf** [comment]
Ich war mit meinen eigenen Arbeiten etwas ausgelastet, daher hatte ich hier noch nicht reagiert ^.^ Habe gesehen, dass du einen PR eingereicht hast, daher spare ich mir hier meinen Input dazu. :D

**Comment by kreuvf** [comment]
Sollte mit den jüngsten Änderungen abgeschlossen sein. Falls nicht, bitte melden.
