### ISSUE TITLE
Getroffene Trefferzone auswürfeln lassen?

### ISSUE THREAD

**Issue by Voidi** [kreuvf/roll20-character-sheets#114]
Ist die Funktion implementiert das man sich die getroffene Trefferzone auswürfeln lassen kann (inklusive des 'nachschlagens' der Zone).
Wenn möglich sogar Automatisch im normalen Schadenswurf inkludiert?

Also im Prinzip: ich drücke auf den entsprechenden Knopf und im Chat wird z.B. angezeigt: "10 Schadenspunkte in Trefferzone Kopf"
Gibts das schon und ich habs einfach nur übersehen?

**Comment by kreuvf** [comment]
Es gibt Trefferpunkteknöpfe im Nah- und Fernkampf, die genau das macht, was du möchtest. Allerdings muss man jedes Mal wählen, was für einen Gegner man getroffen hat, damit die richtige Tabelle verwendet wird.
