### ISSUE TITLE
Eigenschaften bei Zaubern modifizieren

### ISSUE THREAD

**Issue by mygrexit** [kreuvf/roll20-character-sheets#120]
Hallo zusammen,

es wäre super, wenn man auch bei Zaubern die Eigenschaften auf die gewürfelt wird modifizieren könnte.

Als Elf hat man beispielsweise die Möglichkeit Klugheitsproben durch Intuition zu ersetzen (bis max. 2x IN).

Danke für das tolle Tool :-)

**Comment by kreuvf** [comment]
Danke für dein Feedback. Bist mit dem Wunsch nicht der Erste ^_^

Duplikat von #32.

**Comment by kreuvf** [comment]
Wird geschlossen, da Duplikat. :)
