### ISSUE TITLE
Evade base value missing on "Grundwerte" tab

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#14]
The evade base value (Ausweichen-Basiswert, s. WdH 20) is missing on the Grundwerte tab.

**Comment by kreuvf** [comment]
The DSA4.1 editors striked yet again: WdH, p. 20 explicitly mentions such base value (as does the official character sheet) and also that special skills such as Evade I to III influence this value. WdS, p. 66 on the other hand (which IMHO should have priority, see calculation below) only knows modifiers to the evasion check.

The difference between both ways to handle evasion can be seen in the case of an evasion of a lucky strike with a sword (parry value gets halved):
# Examples: Directed Evasion of a Lucky Strike with a Sword
## Evade II, PA base 8, BE 2
* WdS Variant
	* PA base: 8
	* PA base halved: 4
	* Distance class N: +4
	* BE: +2
	* Evade II: -6
	* Check against 4 aka success at 1 to 4 (20% success chance)
* WdH variant
	* Evasion value: 8 + 6 - 2 = 12
	* Evasion value halved: 6
	* Distance class N: +4
	* Check +4 against 6 aka success at 1 to 2 (10% success chance)

## Example 2: Evade III, PA 8, BE 0
* WdS variant
	* PA base: 8
	* PA base halved: 4
	* Distance class N: +4
	* Evade III: -9
	* Check -5 against 4 aka success at 1 to 9 (45% chance)
* WdH variant
	* Evasion value: 8 + 9 = 17
	* Evasion value halved: 9
	* Distance class N: +4
	* Check +4 against 9 aka success at 1 to 5 (25% chance)

It's clear that even an evasion master can only evade 1/4 of all lucky strikes in the WdH variant, while it's almost half of all cases in the WdS variant. Currently, I am leaning towards the WdS way of using evasion; that would make an extra evasion base value superfluous and would also allow to have an evasion-based light fighter. Agile ("Flink") gives another -1 modifier (or adds +1 to the base value) and every full 3 talent points above 9 in "acrobatics" does the same. In comparison to a master fighter (TaW swords 14, AT/PA = 7/7),  would allow to parry with a value of 8 in the above examples, shields not even considered. I am confident that the editors favour the WdS variant as well for the sake of balancing.

**Comment by Markus1204** [comment]
A few more Informations in the Box that shows the results would be nice...

**Comment by kreuvf** [comment]
This will take some more time (~two weeks), but I'm on it.

**Comment by kreuvf** [comment]
So, as you may have noticed, this has the label "top priority" right now. I have made my first experience with Sheet Worker Scripts and can say that it should be without doubt possible to implement both systems (WdH and WdS). I will set WdH as the default. But, to half-fix this issue I will use your advice and add more information to the box. This will be the first thing I will work on once I restart working on the character sheet in ~October.

**Comment by kreuvf** [comment]
Looks kinda ugly now, but contains all the information used for the evasion check.

![20171013_ausweichen-roll-template](https://user-images.githubusercontent.com/518136/31562307-33109a78-b05b-11e7-95ed-745b63b34756.png)

The "Hinweise für Ausweichen-Proben." contains quite a lot of text with an explanation of what is going on ;D
