### ISSUE TITLE
Repräsentationswahl wird nicht berücksichtigt

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#145]
> @kreuvf Erstmal Vielen Dank für dieses tolle neue Feature! Super umgesetzt (auch mit der Anzeige der Ersetzung).
> Wollte es direkt ausprobieren, bei zwei (meiner) Zauber (FlimFlam und Ruhe Körper) scheint es nicht zu klappen, bin nicht sicher, ob ich was falsch gemacht habe oder ob es ein Bug ist. 
> ![ScreenshotRoll20](https://github.com/kreuvf/roll20-character-sheets/assets/98403677/0a99797b-cdff-4301-94b8-0b12c16bf5ee)

_Originally posted by @adrianbens in https://github.com/kreuvf/roll20-character-sheets/issues/32#issuecomment-2112441485_

**Comment by kreuvf** [comment]
Flim Flam und Ruhe Körper zeigen bei mir das gleiche Problem. Das Problem tritt noch bei weiteren Zaubern auf, Liste folgt.

**Comment by kreuvf** [comment]
Die folgenden Zauber sind betroffen:

* Animatio (siehe auch #138 ...)
* Auris Nasus Oculus
* Band und Fessel
* Beherrschung brechen
* Bewegung stören
* Dichter und Denker
* Eigenschaft wiederherstellen
* Elementarer Diener
* Flim Flam
* Fluch der Pestilenz
* Gefäß der Jahre
* Harmlose Gestalt
* Hartes schmelze
* Heilkraft bannen
* Hellsicht trüben
* Höllenpein
* Illusion auflösen
* Klarum Purum
* Körperlose Reise
* Kraft des Erzes
* Limbus versiegeln
* Madas Spiegel
* Magischer Raub
* Metamagie neutralisieren
* Metamorpho Felsenform
* Metamorpho Gletscherform
* Murks und Patz
* Objecto obscuro
* Objekt entzaubern
* Pestilenz erspüren
* Ruhe Körper
* Schleier der Unwissenheit
* Seelentier erkennen
* Staub wandle
* Stimmen des Windes
* Tempus Stasis
* Unberührt
* Veränderung aufheben
* Verständigung stören
* Verwandlung beenden
* Wand aus Flammen
* Warmes Blut
* Warmes Gefriere
* Weiches erstarre

Die folgenden Zauber sind betroffen, aber aufgrund unpassender Eigenschaften macht sich das nicht bemerkbar:

* Ängste lindern
* Auge des Limbus
* Bärenruhe
* Beschwörung vereiteln
* Böser Blick
* Dämonenbann
* Eigne Ängste
* Einfluss bannen
* Eins mit der Natur
* Erinnerung verlasse dich
* Granit und Marmor
* Herbeirufung vereiteln
* Herr über das Tierreich
* Herzschlag ruhe
* Hilfreiche Tatze
* Iribaars Hand
* Komm Kobold Komm
* Krabbelnder Schrecken
* Krähenruf
* Kraft des Humus
* Krötensprung
* Lach dich gesund
* Langer Lulatsch
* Last des Alters
* Levthans Feuer
* Lunge des Leviatan
* Paralysis
* Satuarias Herrlichkeit
* Schadenszauber bannen
* Stein wandle
* Sumus Elixiere
* Tiere besprechen
* Tlalucs Odem
* Totes handle
* Unsichtbarer Jäger
* Weisheit der Bäume
* Zorn der Elemente
* Zunge lähmen

Fazit: Es müssen noch deutlich mehr Aufräumarbeiten unter der Haube durchgeführt werden ^.^ Wahnsinn, dass das nicht während meiner Tests aufgefallen ist :cry:

**Comment by Triqueon** [comment]
Siehe entsprechender #146 : Das sind alle Zauber bei denen der interne Name und der Array-key im spellsData Feld auseinander gehen. Ursache war hier die Verwendung von nameInternal anstatt trigger an einer entsprechenden Codestelle, damit sollte das Problem vorerst behoben sein.

**Comment by kreuvf** [comment]
> Siehe entsprechender #146 : Das sind alle Zauber bei denen der interne Name und der Array-key im spellsData Feld auseinander gehen. Ursache war hier die Verwendung von nameInternal anstatt trigger an einer entsprechenden Codestelle, damit sollte das Problem vorerst behoben sein.

S. Diskussion dort, die Behebung ist komplizierter und ich arbeite schon an einem WIP :) Da das aktuelle Video aber "nur" noch geschnitten werden muss, geht das aktuell vor~
