### ISSUE TITLE
DSA 4.1 Charachter sheet Version 20240609 talents are bugged

### ISSUE THREAD

**Issue by Broetchenholer** [kreuvf/roll20-character-sheets#148]
Hi,

i think you are the author of the DSA 4.1 charachter sheet. Thank you for your work :)

Looks like the newest update broke the character sheet for talents, in our group rolling talents results in the attributes just being added, rolls justb eing added, and not properly checked against each other:

![grafik](https://github.com/kreuvf/roll20-character-sheets/assets/172539024/9a945983-3397-49a9-9d17-9d0a915151c1)
![grafik](https://github.com/kreuvf/roll20-character-sheets/assets/172539024/c1f0daaf-3fda-4920-b59c-6fa39eee987c)

Fighting and attribute rolls is fine, but talents don't work.

**Comment by kreuvf** [comment]
Fix ist seit gestern Abend bei Roll20 eingereicht ^.^

https://github.com/Roll20/roll20-character-sheets/pull/13011

**Comment by kreuvf** [comment]
Talentwürfe mit eBE funzen im Übrigen auch problemlos, hatte beim letzten Update aber auch nur die dann getestet. Total dämlicher Bug, aber nichts Schlimmes. Ich hoffe, dass Roll20 das heute gegen ~21 Uhr einbaut und dann sollte das auch direkt live gehen.

**Comment by Broetchenholer** [comment]
Vielen Dank :)
