### ISSUE TITLE
Negative TP/KK values do not influence AT/PA

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#15]
Low strength values not only negatively affect the damage dealt with a certain weapon, but also reduce the corresponding AT/PA values by the same amount. Currently, AT/PA values are unaffected.

Source: WdS, p. 82

**Comment by Koizumi85** [comment]
Ich denke das hier werde Ich als nächstes angehen. In dem Zuge würde Ich dann gerade die TP/KK Berechnung ebenfalls in Sheetworker überführen. Die Einberechnung der Modifikatoren kann Ich dann relativ problemlos in meiner calculateCombatValues Funktion machen, die Ich im Zuge der Schild- und Parierwaffen-Arbeiten hinzugefügt habe.

**Comment by Koizumi85** [comment]
Im verlinkten Commit erledigt. Die Version (99999999) hab ich jetzt für dev-zwecke genommen und muss dann entsprechend vor PR Richtung roll20 noch geändert werden

**Comment by kreuvf** [comment]
TP/KK für Schilde (Schildangriff) ist übrigens 13/3, falls du die Info an anderer Stelle gebrauchen kannst :X

**Comment by Koizumi85** [comment]
Umsetzung zu finden hier: 
https://github.com/Koizumi85/roll20-character-sheets/tree/dsa4.1-tpkk-mod

**Comment by kreuvf** [comment]
Habe das mal händisch auf den aktuellen Stand gebracht, noch ungetestet: https://github.com/kreuvf/roll20-character-sheets/tree/pre-dsa4.1-modifiers-shield-attack

**Comment by kreuvf** [comment]
Dein Branch https://github.com/Koizumi85/roll20-character-sheets/tree/dsa4.1-tpkk-mod müsste prinzipiell ja identisch mit meinem pre-dsa4.1-modifiers-shield-attack sein. Ist er aber nicht.

Habe das erneut force-gepusht, um einen sehr großen, aber unbedeutenden Unterschied schon mal zu entfernen, aber bei dem Rest wäre es mir lieber, wenn du da nochmal drüberschaust. Möglicherweise hast du beim Anpassen was übersehen?

**Comment by Koizumi85** [comment]
Ich bin mir nicht ganz sicher was du meinst. Wenn Ich die beiden Branches compare sind da eigentlich nur Änderungen drin, die Ich in meinem Branch gemacht hab. Die dürften bei dir ja noch nicht drin sein.

**Comment by kreuvf** [comment]
Ich hatte in meinem Branch sämtliche Änderungen aus deinem Commit https://github.com/Koizumi85/roll20-character-sheets/commit/fb09b5863ca60fb847379d32bf70841567496a32 übernommen. Wenn ich das aber richtig sehe, hast du eben bestimmte Hunks aus dem diff in deinem aktualisierten Branch nicht übernommen. Insbesondere aber die Ersetzungen für die Attribute `NKWx_SB` sehen mir sehr danach aus, dass die drin sein sollten (erste acht Hunks).

**Comment by kreuvf** [comment]
Ich hatte in meinem Branch sämtliche Änderungen aus deinem Commit https://github.com/Koizumi85/roll20-character-sheets/commit/fb09b5863ca60fb847379d32bf70841567496a32 übernommen. Wenn ich das aber richtig sehe, hast du eben bestimmte Hunks aus dem diff in deinem aktualisierten Branch nicht übernommen. Insbesondere aber die Ersetzungen für die Attribute `NKWx_SB` sehen mir sehr danach aus, dass die drin sein sollten (erste acht Hunks).

**Comment by kreuvf** [comment]
Ich habe mich jetzt entschieden, auf deinem Stand weiterzumachen :) Bislang sehe ich hier keine Probleme, der Code tut, was er soll.

**Comment by kreuvf** [comment]
Bin soweit damit durch und konnte keine Probleme finden. Siehe https://github.com/kreuvf/roll20-character-sheets/tree/pre-dsa4.1-tpkk-mod.
