### ISSUE TITLE
Alle TaWs ungleich Null gelöscht

### ISSUE THREAD

**Issue by Necrask** [kreuvf/roll20-character-sheets#150]
Moin,

ich habe unser altes Roll20 DSA 4.1 Game reaktiviert, um meinen alten Char zusehen und musste dann fest stellen, dass alle TaWs, die ich eingetragen habe, gelöscht worden sind. Dies bedeutet, da ich keinen On-Paper-Backup für den Char habe, mir dieser quasi verloren gegangen ist, da ich mich nicht mehr an die TaW-Verteilung erinneren kann.

IIRC habe ich die TaWs mit +X damals eingetragen.

Beispielhaft:
![grafik](https://github.com/kreuvf/roll20-character-sheets/assets/67807029/babdad17-e326-47c7-9ce9-44bf72a46dec)
![grafik](https://github.com/kreuvf/roll20-character-sheets/assets/67807029/8253f4bd-8379-4eb3-8486-c1448bd1f515)

Andere Chars, die nur eine Zahl eingetragen haben, haben ihre TaWs behalten.
![grafik](https://github.com/kreuvf/roll20-character-sheets/assets/67807029/7a4120de-84e3-4ff0-8789-926cf00ba28c)

**Comment by kreuvf** [comment]
> Moin,
> 
> ich habe unser altes Roll20 DSA 4.1 Game reaktiviert, um meinen alten Char zusehen und musste dann fest stellen, dass alle TaWs, die ich eingetragen habe, gelöscht worden sind. Dies bedeutet, da ich keinen On-Paper-Backup für den Char habe, mir dieser quasi verloren gegangen ist, da ich mich nicht mehr an die TaW-Verteilung erinneren kann.

Das tut mir sehr leid :sob: Ich arbeite seit Jahren an dem Bogen und eines meiner obersten Ziele ist es, Datenverlust zu verhindern. :cry:

Es könnte sein, dass die Werte noch existieren, aber spätestens, wenn du den TaW einmal angefasst hast, ist er überschrieben. Aus welchem Jahr war das Spiel? Welche Version hatte der Bogen vorher? Ich kann mich nicht daran erinnern, dass die TaWs irgendwie konvertiert wurden. Ich schaue mal, ob ich das reproduzieren kann.

Bitte niemals den Charakter nur auf Roll20 haben, die Charaktere sind dort nicht übermäßig sicher. :pensive: Also, ganz unabhängig von deinem konkreten Fall.

> IIRC habe ich die TaWs mit +X damals eingetragen.

Es könnte sein, dass die Textfelder umgestellt wurden von "Freitext" auf "nur Zahlen" :thinking:

Hinweis für die Reaktivierung alter Spiele/Bögen, um dir zukünftigen Datenverlust zu ersparen:

* Spiel in Roll20 reaktivieren
* Roll20 Characters (ehemals "Character Vault") nutzen:
  * Charakter aus dem reaktivierten Spiel in Characters laden
  * falls noch nicht geschehen: neues Spiel mit dem gleichen Charakterbogen anlegen
  * Charakter aus Characters ins neue Spiel importieren
* Charakter im neuen Spiel öffnen und prüfen, ob alles funktioniert
  * falls nicht: mir Bescheid sagen

Damit wird immer nur eine Kopie des Charakters verwendet. Charaktere werden im Spiel erst dann aktualisiert, wenn sie das erste Mal geöffnet werden. Theoretisch™ sollte der Charakter in dem reaktivierten Spiel also, solange er nicht geöffnet wurde, intakt bleiben. :face_exhaling: Mir wäre lieber, sowas wäre nicht nötig.

**Comment by Necrask** [comment]
> Aus welchem Jahr war das Spiel? Welche Version hatte der Bogen vorher?
Ich kann mich nicht mehr an die Char-Sheet Version erinnern, aber das Spiel wurde zuletzt im Oktober 2021 gespielt.

> Hinweis für die Reaktivierung alter Spiele/Bögen, um dir zukünftigen Datenverlust zu ersparen:
Ich habe das Vault benutzt und den Char in ein neues Spiel geladen und habe weiterhin leere Felder. Ich habe die Felder auch nicht angefasst.

Vielen Dank schon mal. Bisher ist mir in Roll20 noch nie ein Char abhanden gekommen - gut das sind alles ja D&D5e chars.

**Comment by kreuvf** [comment]
> > Aus welchem Jahr war das Spiel? Welche Version hatte der Bogen vorher?
> 
> Ich kann mich nicht mehr an die Char-Sheet Version erinnern, aber das Spiel wurde zuletzt im Oktober 2021 gespielt.

Okay, also schon zu "meiner Zeit". Möglicherweise ist das ein "Feature" von Roll20, das beim Reaktivieren etwas gemacht wird, das sonst nicht gemacht wird, z. B. ein "sanity check" aller Felder :thinking:
 
> > Hinweis für die Reaktivierung alter Spiele/Bögen, um dir zukünftigen Datenverlust zu ersparen:
> 
> Ich habe das Vault benutzt und den Char in ein neues Spiel geladen und habe weiterhin leere Felder. Ich habe die Felder auch nicht angefasst.

Ja, das wird auch immer wieder passieren, wenn Roll20 keinen einmaligen Fehler hatte. Du solltest dir damit aber auf jeden Fall die Daten im reaktivierten Spiel erhalten, bevor der Charakter also erstmalig geöffnet wurde.

Ich schaue später mal, dass ich eine kurze Anleitung poste, wie du schauen kannst, ob die Daten tatsächlich weg sind oder nur nicht angezeigt werden :slightly_smiling_face:

**Comment by kreuvf** [comment]
Ich habe mal ein bisschen herumprobiert und bin verhalten optimistisch, dass deine Daten noch da sind. Aber eines nach dem anderen.

# Ursachenforschung
Ich habe mir mal meinen Sandbox-Charakter genommen und einfach geschaut, was passiert, wenn ich beim TaW Abrichten "+4" eintrage und beim TaW Ackerbau "4". Ergebnis:

* Würfelwürfe funktionieren in beiden Fällen.
* Unter "Attributes & Abilities" sind die beiden Attribute (noch, s. u.) nicht zu sehen (werden erst angelegt, wenn das Attribut erstmalig gesetzt wird).

Ich habe den Charakterbogen dann einmal geschlossen und wieder geöffnet und mir zeigte sich das folgende Bild:

* TaW Abrichten war leer
* TaW Ackerbau war weiterhin "4"
* Unter "Attributes & Abilities" sind beide Attribute angelegt. TaW_abrichten mit "+4", TaW_ackerbau mit "4".

Ursache ist also das "+" im Wert.

# Fehlerbehebung
## Weg 1: Klicken und Gucken
Der Wert wird trotz der fehlenden Anzeige genutzt, weshalb du einfach alle Talente einmal durchwürfeln kannst. In der Wurfvorlage findet sich ja der TaW und dann kannst du das danach einfach händisch eintragen. Also: Einfach mal würfeln, obwohl da kein TaW steht, du siehst im Wurf, wie der TaW war/ist.

## Weg 2: Technischer Weg
Alternativ kannst du an deine vermeintlich verlorenen Daten kommen, wenn du Tab "Attributes & Abilities" nachschaust:
![image](https://github.com/kreuvf/roll20-character-sheets/assets/518136/a941be5e-b8b2-45eb-a1cd-3484a4d0e0b0)

Das dauert möglicherweise etwas mit dem Laden, aber du findest dort (zur Not "Strg + F" nach "TaW") die entsprechenden Zeilen mit den Werten. Die jeweiligen Werte finden sich dann in der linken Box.

![image](https://github.com/kreuvf/roll20-character-sheets/assets/518136/eb22acdd-65ff-44b8-960e-2b44ae30a346)

Am einfachsten sollte es sein, wenn du das Pluszeichen entfernst, dann den Bogen einmal schließst und wieder öffnest. Die fehlenden Werte sollten dann wieder da sein.

# Kein Bug?
Das ist ziemlich sicher ein Roll20-Verhalten, aber ich könnte das charakterbogenseitig abfangen, indem ich Zahlenwerte, die eingegeben werden, genauer prüfe und gegebenenfalls nur korrigiert speichere. Siehe dazu #151. Melde dich bitte, ob du deine Werte wiederfinden konntest. Falls ja, kann ich das hier schließen :)

**Comment by Necrask** [comment]
🤦 auf die Attributseite hätte ich selber kommen können. Ja da waren diese noch eingetragen und nach dem ich das + entfernt habe erschienen sie auch im Sheet wieder.

Aber 2021 wurden die Werte auch mit dem Plus noch angezeigt, 🤔 

Vielen Dank dir, bin echt froh, dass der Char gerettet werden konnte!

**Comment by kreuvf** [comment]
> 🤦 auf die Attributseite hätte ich selber kommen können. Ja da waren diese noch eingetragen und nach dem ich das + entfernt habe erschienen sie auch im Sheet wieder.
> 
> Aber 2021 wurden die Werte auch mit dem Plus noch angezeigt, 🤔
> 
> Vielen Dank dir, bin echt froh, dass der Char gerettet werden konnte!

:blush:

Bitte denk trotzdem daran, wichtige Charaktere nicht allein nur auf Roll20 zu behalten.

Wie gesagt: Das ist wahrscheinlich eine Roll20-seitige Sache. Habe es auch gerade nochmal nachvollzogen anhand von `TaW_abrichten` (Historie ohne Auslassungen in der Mitte!):

* 8010d2b9ba2 (Kreuvf 2017-02-24 13:23:42 +0100):
`<input type="number" class="sheet-talent-taw" name="attr_TaW_abrichten" min="-4" value="0">`
* ef340b23593 (Kreuvf 2024-01-01 21:34:53 +0100):
`<input type="number" class="talent-taw" name="attr_TaW_abrichten" min="-4" value="0">`
* 14ee94e9b4e (Kreuvf 2024-01-21 18:01:34 +0100):
`<input type="number" class="talent-taw" name="attr_TaW_abrichten" min="-4" value="0">`
* a5d3b8e545a (Kreuvf 2024-01-21 20:44:45 +0100):
`<input type="number" class="talent-taw" name="attr_TaW_abrichten" min="-4" value="0">`

Das einzige, was sich also in der Zeit an dieser Stelle geändert hat, ist eine Umbenennung der CSS-Klasse, die aber durch den Wechsel vom Legacy Parsing bedingt war und keine Auswirkungen auf die Daten in dem Feld hat. Es kann sogar so sein, dass die Technologie, die Roll20 benutzt, mittlerweile etwas anders macht :D
