### ISSUE TITLE
[DSA 4.1] There are damage rolls for different target areas like head or arm but no roll to determine the area

### ISSUE THREAD

**Issue by seism0saurus** [kreuvf/roll20-character-sheets#152]
Hi,

I'm new to the character sheet for DSA 4.1 but experienced with the system itself.

As far as i can see, there are damage rolls for different target areas like head or arm but no roll to determine the area itself (Trefferzone).
![grafik](https://github.com/user-attachments/assets/2543db86-4eed-4351-9cbb-ca9089bb517a)

It would be nice to have a button to roll the area before rolling the specific damage.

Never mind. I misunderstood the UI.
The buttons are for damage i take.
The target areas for my opponents are behind the button for damage.
![grafik](https://github.com/user-attachments/assets/aeba1386-a5fb-4d81-a6a9-f2829fd21d77)

This can be closed. Sorry for the noise

**Comment by seism0saurus** [comment]
Never mind

**Comment by kreuvf** [comment]
Kein Ding ^_^ Hast du vielleicht einen Vorschlag, wie ich das deutlicher für Neulinge machen kann?
