### ISSUE TITLE
DSA4.1: Schnellladen hat keine Auswirkung

### ISSUE THREAD

**Issue by egnrse** [kreuvf/roll20-character-sheets#155]
Die Fernkampfsonderfertigkeit _Schnellladen_ hat keine Auswirkung auf die angezeigte _Dauer inkl. Laden_ im Kampf>Fernkampf Tab. Getestet in einem ganz neuen Spiel mit Bogen und Armbrust.

(Wenn ich mich richtig erinnere hat das schon einmal funktioniert (innerhalb der letzten 2.5 Jahre), vielleicht hat ein update das zerstört)

**Comment by kreuvf** [comment]
Das liegt daran, dass das nicht eingebaut ist und auch nie war. :astonished: 

Sicher, dass du das nicht mit Scharfschütze/Meisterschütze und/oder Schnellschuss verwechselst?

**Comment by egnrse** [comment]
Hmm, danke... es ist aber als Kampfsonderfertigkeit angeführt (wenn ichs richtig sehe). Siehe screenshot:
![image](https://github.com/user-attachments/assets/81203909-8984-4dc5-9e18-58de2635805d)

vlt eine Notiz dazu machen das es nicht berücksichtigt wird?

**Comment by kreuvf** [comment]
> Hmm, danke... es ist aber als Kampfsonderfertigkeit angeführt (wenn ichs richtig sehe).
> [...]
> vlt eine Notiz dazu machen das es nicht berücksichtigt wird?

Ja, das ist definitiv der richtige Weg. Ich denke, ich sollte bei den Kampfsonderfertigkeiten auch mal klar und deutlich markieren, ob etwas vom Bogen berücksichtigt wird.

Danke für deinen Input :relieved:

**Comment by kreuvf** [comment]
Zufrieden mit der aktuellen Lösung? :)
