### ISSUE TITLE
[DSA 4.1] Inconsistent use of Sinnenschärfe

### ISSUE THREAD

**Issue by cegge** [kreuvf/roll20-character-sheets#156]
Referencing this PR: https://github.com/Roll20/roll20-character-sheets/pull/13320

The term used by the publisher for the talent is "Sinnenschärfe". In later versions it is called "Sinnesschärfe", which would be the correct german word. In the sheet both words "Sinnenschärfe" and "Sinnesschärfe" are used, which is irritating. 

@kreuvf wants to use the word "Sinnenschärfe" (see [linked PR](https://github.com/Roll20/roll20-character-sheets/pull/13320)). If this is the word we want to stick to, we should change all other instances of "Sinnesschärfe" to "Sinnenschärfe". If there is a decision on this, I can create another PR.

**Comment by kreuvf** [comment]
Hier können wir ruhig weiter auf Deutsch schreiben ^^ Wo im Charakterbogen wird denn noch "Sinnesschärfe" verwendet? :thinking: 

Kannst den PR dann ruhig gegen meinen Fork machen, das ist eine Kleinigkeit, die ziehe ich dann direkt mit rein und ich kümmere mich dann auch gern um die restlichen Formalitäten :D Dringend ist es ja nicht, oder?

**Comment by cegge** [comment]
Im Charakterbogen steht ausschließlich "Sinnesschärfe": https://github.com/kreuvf/roll20-character-sheets/blob/47668f6b3992024554ceb3fe2e5d1e253871b008/Das_Schwarze_Auge_4-1/dev/html/sheet/section_talente.html#L1047-L1091

In der Anzeige im Chat, sobald man über den Charakterbogen würfelt, steht dann "Sinnenschärfe".  Die internen Variablen und Funktionen sind auch nicht einheitlich benannt, aber das kann ja egal sein. 😅 

Mit restlichen Formalitäten meinst du, dass ich mich nicht um die Versionsnummer kümmern muss?

**Comment by kreuvf** [comment]
Oh, krass! xD Wie betriebsblind man sein kann. Dann muss ich mich erst einmal entschuldigen dafür, dass ich behauptet habe, "Sinnenschärfe" wäre durch deine Änderung nicht überall (also, UI-seitig) geändert. :pensive: Ich war fest davon überzeugt, dass es auf dem Würfelbutton "richtig" ist. Ich kümmere mich im Laufe der Woche nochmal um einen ausführlicheren Kommentar.

Danke schon mal für deinen Beitrag :pleading_face:

**Comment by kreuvf** [comment]
So, jetzt die volle Antwort.

> Im Charakterbogen steht ausschließlich "Sinnesschärfe":
> 
> https://github.com/kreuvf/roll20-character-sheets/blob/47668f6b3992024554ceb3fe2e5d1e253871b008/Das_Schwarze_Auge_4-1/dev/html/sheet/section_talente.html#L1047-L1091
> 
> In der Anzeige im Chat, sobald man über den Charakterbogen würfelt, steht dann "Sinnenschärfe". Die internen Variablen und Funktionen sind auch nicht einheitlich benannt, aber das kann ja egal sein. 😅

Gut bemerkt, werde das auf jeden Fall für's nächste Release anpassen.

> Mit restlichen Formalitäten meinst du, dass ich mich nicht um die Versionsnummer kümmern muss?

Ja, das meine ich. Etwas detaillierter fallen auf jeden Fall die folgenden Arbeiten an:

* Anpassung der Versionsnummer
* Verfassen der Hinweise zur neuen Version
* Prüfung auf Notwendigkeit einer Migrationsfunktion
* optional: Migrationsfunktion schreiben (und testen!)

Für mich hört es da aber nicht auf, denn nach dem Stellen des PR geht es weiter:

* Posts auf Social Media (Mastodon, Telegram, Twitter, Orkenspalter, dsaforum)
* optional: Videoproduktion mit allem, was dazugehört (beschränkt auf "große" Veränderungen)

Grundsätzlich zu diesem Thema: Es gibt immer noch viele Altlasten im Bogen und ich scheue mich in der Regel davor, Änderungen vorzunehmen, die eine Migrationsfunktion benötigen, wenn absehbar ist, dass ich den entsprechenden Bereich ohnehin wieder ändern werde, womit erneut eine Migrationsfunktion nötig werden würde. Die ganzen internen Namen bestimmter Talente sind da genau so eine Sache.

Vielleicht hast du gesehen, was ich bei der [Beschwörungsmagie auf Myranor](https://youtu.be/MzBODgVReOU) gemacht habe: Auf diese Art und Weise sollen nicht nur aventurische Zauber eingebaut werden, sondern perspektivisch auch Rituale, Liturgien und, besonders wichtig für dieses Issue, Talente. Dafür wird auf jeden Fall eine Migrationsfunktion benötigt werden und ich bin bereits sehr glücklich darüber, dass viele, viele, viele Attribute wegfallen werden.
