### ISSUE TITLE
"Grundwerte" are not rounded properly

### ISSUE THREAD

**Issue by YuanRamirez** [kreuvf/roll20-character-sheets#2]
Magic resistance ("Magieresistenz"), Lifepoints ("Lebensenergie"), Stamina ("Ausdauer") and Astral energy ("Astralenergie") are not rounded properly (decimals up to .4 should be rounded down).

**Comment by kreuvf** [comment]
(If I should write in English, please say so.)

Problem bestätigt und lokal bereits behoben. Werde nochmal WdS konsultieren, bisschen testen und das dann in den Branch für diese Woche aufnehmen.
