### ISSUE TITLE
Talents: Pre-Fill Stats of Meta Talents and Gifts

### ISSUE THREAD

**Issue by Markus1204** [kreuvf/roll20-character-sheets#22]
If you have any Meta Talents or Gaves you need to select it from a list but then enter the Features (MU, IN, etc.) on your own... Since for most of this Talents this is fix, it'd be nice if those would be set if you select the Meta-Talent or Gave... If needed, it can be changed as for every other talent...

It is not a must, but a nice to have...^^

**Comment by kreuvf** [comment]
Ist nicht schön, wie es momentan ist, funktioniert immerhin aber. Daher ist die Priorität niedrig. Bei Metatalenten würde ich sogar so weit gehen die automatisch berechnen zu lassen. Richtig nice, aber vermutlich kaum umzusetzen, wäre es, wenn man sogar eigene Metatalente definieren könnte ;D

**Comment by Markus1204** [comment]
Das mit den eigenen Talenten... sowas ähnliches gibts bereits im DSA 5 Charakterbogen... Da besteht die Möglichkeit, Talente anzulegen (frei) und darauf zu würfeln... Metatalente automatisch berechnen wäre cool, ist aber kein muss...^^
