### ISSUE TITLE
Bug: DSA 4.1 Fernkampfrechner zeigt bei Erleichterungen die Probe als Misslungen

### ISSUE THREAD

**Issue by Markus1204** [kreuvf/roll20-character-sheets#26]
Mit dem funktionierenden Fernkampfrechner errechnete Attacken gelten IMMER als Misslungen wenn der Modifikator ein Minus (-) beinhaltet, also eine Erleichterung. In diesem Fall steht jedes Mal "Misslungen" in der Box obwohl das Würfelergebnis aussagt das die Probe gelungen ist...

**Comment by kreuvf** [comment]
Danke für die Meldung. ^^

Den Bug habe ich am WE selbst gefunden und der ist im aktuellen Pull Request bereits behoben. 

Siehe Commit c40ae4c und Pull Request Roll20/roll20-character-sheets#2968

Ich schließe das Issue daher jetzt auch. Falls dieser oder ein anderer Bug mit Version 2017-09-03 auftritt, mache bitte ein neues Issue auf.
