### ISSUE TITLE
Tabellenabstände vergrößert

### ISSUE THREAD

**Issue by ap3h3ad** [kreuvf/roll20-character-sheets#29]
Hi,

mit dem letzten Update der Roll20-Software (charactermancer update) haben ein paar Charakterbögen Probleme mit Tabellenabständen bei Roll Templates, so auch der DSA 4.1-Bogen. Wenn man auf Talente würfelt, sieht das Ergebnis ziemlich gestreckt aus und etwas unschön. Da ich das Problem mit dem Splittermondbogen auch hatte, weiß ich, dass es relativ leicht zu lösen ist. In der CSS-Datei müssen die Tabellen-Klassen spezifiziert werden, also z.B. muss aus

.sheet-rolltemplate-DSA-Nahkampf-AT table.sheet-templates-succ-crc,

.sheet-rolltemplate-DSA-Nahkampf-AT .sheet-templates-succ-crc,

werden. So hat es jedenfalls bei mir funktioniert.

Thread zum Problem im Roll20-Forum: https://app.roll20.net/forum/post/6543544/roll-template-tables-larger-since-update

Thread mit Lösungen im Roll20-Forum: https://app.roll20.net/forum/post/6532499/bootstrap-and-jqueryui-updates

Liebe Grüße

**Comment by kreuvf** [comment]
Danke für den Hinweis. Habe es gerade mal mit den Developer Tools probiert, aber der einzige Unterschied, den ich sehe, ist, dass die Hintergrundfarben der Tabellen nicht mehr angewendet werden ^.^ Habe das auch mal mit alten Screenshots verglichen und konnte höchstens minimale Unterschiede feststellen.

Kannst du mir vielleicht einen Screenshot davon hier hochladen, damit ich das Problem auch sehen kann?

**Comment by ap3h3ad** [comment]
Hast du inzwischen irgendetwas gemacht? In meiner Roll20-Kampagne sieht jetzt wieder alles normal aus. Entschuldige die Störung. ^^
