### ISSUE TITLE
"BE" does not affect initiative

### ISSUE THREAD

**Issue by YuanRamirez** [kreuvf/roll20-character-sheets#3]
"Behinderung" (BE) (obstruction?) and active weapon modifiers are not taken into consideration when rolling for initiative (INI-Basis - BE + Mod + 1d6 = INI)

**Comment by kreuvf** [comment]
Initiativebestimmung ist (leider :P) auch ein relativ kompliziertes Kapitel in DSA  4.1. Da die Initiative von der Behinderung abhängt, gilt zusätzlich zu Einflüssen auf die Initiative alles, was ich schon in dem anderen Issue zur Behinderung schrieb (#4).

PS: "Behinderung" ist eher "encumbrance".

**Comment by YuanRamirez** [comment]
Ahja, okay. Dann auch hier: werde an meine Spielgruppe weitergeben, dass wir da selbst ein bisschen drauf achtgeben müssen.

PS: Jetzt, wo du's sagst, macht encumbrance auch mehr Sinn XD

**Comment by kreuvf** [comment]
Prinzipiell in meinem neuesten Branch bereits behoben, aber ich werde im Zuge dessen den Nahkampftab insgesamt ein wenig überarbeiten. Grundlegende Überarbeitung steht dann weiterhin aus.

**Comment by kreuvf** [comment]
Im Zuge von https://github.com/Roll20/roll20-character-sheets/pull/2704 behoben.
