### ISSUE TITLE
Automatisches einlesen der XML aus Heldentool?

### ISSUE THREAD

**Issue by Markus1204** [kreuvf/roll20-character-sheets#30]
Was auch sehr schön wäre (auch wenn hier momentan alles auf Eis liegt), wäre wenn man die XML Datei aus dem Heldentool direkt in den Sheet laden könnte und alle Werte, Liturgien, Zauber, Ausrüstung etc. automatisch in den Sheet übernommen würde...^^

**Comment by kreuvf** [comment]
Die Idee besteht bereits, siehe mein Video [Update 2017-12-08](https://youtu.be/nMkEzXe-HLY?t=5m00s), siehe auch Issue #20, da ist es bereits aufgenommen. :)

Daher mache ich dieses Issue auch zu.
