### ISSUE TITLE
Nachteile: Tollpatsch, Wilde Magie

### ISSUE THREAD

**Issue by Lorindion** [kreuvf/roll20-character-sheets#31]
Ich habe Spieler in der Gruppe, die diese Nachteile bevorzugen. Problem ist nun, dass in diesen Würfen cf>=19 sein müsste. Und dies auch nur für diese Spieler. Die Warnmeldung könnte gleich bleiben, damit hätte niemand ein Problem.

Kann man irgendwo eine Checkbox für die Nachteile einführen und dann die Proben speziell für die Spieler ändern?

Andernfalls muss man JEDE Probe dieser Spieler auf 19en untersuchen, was im Overlay nicht wirklich schön ist.

Ich kann mir vorstellen, es selbst zu programmieren, wenn man mir eine kurze Einführung geben könnte.

**Comment by kreuvf** [comment]
Prinzipiell ist cf>=19 kein Problem. Auch die Anzeige im Wurf ist kein Problem, dazu muss nur die Wurfvorlage angepasst werden. Im Grunde ist das bereits angedacht (siehe Post-SWS Conversion in Issue #20), ich lasse das aber als eigenständiges Issue offen. Kurzfassung: Bevor ich noch weiter Krams hinzufüge auf die alte Art und Weise, möchte ich den Bogen erst konvertieren, da ich mir sonst doppelte Arbeit machen müsste. Rechne nicht vor Ende des Jahres damit ... :(

Abhilfe könnte die Nutzung der 3D-Würfel machen, da ihr so den Wurf direkt sehen könnt.

Eine kurze Einführung kostet leider deutlich mehr Zeit als es direkt selbst zu machen ^.^ Zudem bräuchtest du zum Testen einen Roll20-Account mit Pro-Abo und ich gehe davon aus, dass du das ohnehin nicht hast.

**Comment by kreuvf** [comment]
Da du in Issue #20 deine Mithilfe angeboten hast, empfehle ich dir als "Aufwärmübung" statt mir die Konvertierungsarbeit abzunehmen Tollpatsch und Wilde Magie einzubauen.

Ich stelle mir das (vorerst) so ähnlich vor wie auf dem V/N-&-SF-Tab im Kampftab. Relevante, das heißt im Charakterbogen mit automatischer Berücksichtigung versehene, Vor- und Nachteile erhalten einen eigenen Bereich, nur eben im Fertigkeiten-Tab (die Benennung ist irreführend und du darfst das auch gerne ebenfalls in V/N & SF ändern ;D).

So könnte das dann aussehen:
![20180810_roll20_dsa4_tollpatsch_wilde_magie_mockup](https://user-images.githubusercontent.com/518136/43976837-55850dcc-9ce2-11e8-95b3-69195f5f3641.png)

**Comment by kreuvf** [comment]
Kurze Ankündigung, dass diese Änderungen demnächst™ umgesetzt werden.
