### ISSUE TITLE
Elfische Zauber

### ISSUE THREAD

**Issue by Lorindion** [kreuvf/roll20-character-sheets#32]
Laut elfischer Repräsentation dürfen Elfen einmal KL in IN umwandeln.

Zitat Liber Cantiones S. 8:

"In der Zauberprobe darf einmal die KL durch IN ersetzt werden, sofern dann nicht alle Proben auf IN abgelegt werden."

Dies ist bei der elfischen Repräsentation nicht umgesetzt, die Standard Eigenschaften werden gesetzt. Ein Ändern wie bei den Talenten ist nicht möglich.

**Comment by adrianbens** [comment]
Ein manuelles Auswählen/Ändern der einzelnen Eigenschaften wäre ja als Minimallösung schön. Gibt es Chancen, dass das demnächst umgesetzt wird?

**Comment by kreuvf** [comment]
> Ein manuelles Auswählen/Ändern der einzelnen Eigenschaften wäre ja als Minimallösung schön. Gibt es Chancen, dass das demnächst umgesetzt wird?

Diese Minimallösung wäre leider nur eine Zwischenlösung zu dem, was ich mir vorgenommen habe, und dafür dann auch noch eine mit dem maximalen Aufwand.

>  Oder könnte man ggf. helfen (sieht nach viel Fleißarbeit aus, die Blöcke für die Eigenschaftsauswahl für jeden Zauber zu schreiben)

Ich denke, wenn die 3W20-Geschichten mit dem Custom Roll Parsing durch sind, dann wäre als Übergangslösung ein Dropdown am Zauber für die Repräsentation sinnvoll. Hier könnte man dann beim Custom Roll Parsing die Repräsentation berücksichtigen. Helfen kannst du mir, indem du mir sagst, ob das für dich eine ausreichend gute Lösung wäre.

ETA dafür kann ich leider nicht zuverlässig nennen. Ich schwanke aktuell noch (nach Abarbeitung der übrigen Themen zu Würfeln und Würfelvorlagen) zwischen einem halbwegs nutzbaren Inventarsystem und der Überarbeitung des Magietabs. :)

Mit den 3W20-Geschichten mit Custom Roll Parsing wird es allerdings schon etwas einfacher, da dann der 3W20-Wurf leichter zu erkennen sein wird. :D

**Comment by adrianbens** [comment]
>Helfen kannst du mir, indem du mir sagst, ob das für dich eine ausreichend gute Lösung wäre.

Vielleicht mal vorneweg, ich nutze das Character Sheet schon eine Weile, und ich weiß dass es ein Fantool ist und bin sehr dankbar dafür.  Meine Erwartungshaltung ist dementsprechend "gering" und ich freue mich (wie vermutlich so viele) über jede Verbesserung. Was sich genau durch das Custom Roll Parsing ändern wird habe ich noch nicht verstanden, eine manuelle Änderung an jedem Zauber einzeln wäre natürlich schon eine große Verbesserung.

**Comment by kreuvf** [comment]
> Vielleicht mal vorneweg, ich nutze das Character Sheet schon eine Weile, und ich weiß dass es ein Fantool ist und bin sehr dankbar dafür. Meine Erwartungshaltung ist dementsprechend "gering" und ich freue mich (wie vermutlich so viele) über jede Verbesserung.

:)

> Was sich genau durch das Custom Roll Parsing ändern wird habe ich noch nicht verstanden, eine manuelle Änderung an jedem Zauber einzeln wäre natürlich schon eine große Verbesserung.

Kommende Änderungen (boosterbedingt verzögert es sich etwas):
> https://www.orkenspalter.de/index.php?thread/36140-dsa4-1-charakterbogen-auf-roll20-net/&postID=1103483#post1103483

**Comment by mygrexit** [comment]
Hallo @kreuvf, ich würde das Thema gerne ansehen und habe mir den Code mal angeschaut. Deine Aufsplittung war der ausschlaggebende Punkt, vorher war mir das echt zuviel :)

Ich habe eine Liste der Zauber in elfischer Repräsentation erstellt, die mindestens 1 x KL, aber nicht mehr als 2 x IN hat:

```
    Abvenenum - KL/KL/FF +Mod
    Aeolitus - KL/CH/KO
    Arcanovi - KL/KL/FF
    Attributo - KL/CH/Eigenschaft
    Axxeleratus - KL/GE/KO
    Balsam - KL/IN/CH +Mod
    Band und Fessel - KL/CH/KK +MR
    Beherrschung brechen - KL/IN/CH +Mod
    Bewegung stören - KL/IN/FF +Mod
    Blick auf Wesen - KL/IN/CH +MR
    Blick in die Gedanken - KL/KL/CH +MR
    Blitz dich find - KL/IN/GE +MR
    Claudibus - KL/FF/KK
    Corpofesso - KL/KK/KK +MR
    Destructibo - KL/KL/FF +Mod
    Dunkelheit - KL/KL/FF
    Firnlauf - MU/KL/GE
    Flim Flam Funkel - KL/KL/FF
    Gedankenbilder - KL/IN/CH
    Harmlose Gestalt - KL/CH/GE
    Hellsicht trüben - KL/IN/CH +MR
    Infinitum - KL/CH/KO +Mod
    Katzenaugen - KL/FF/KO
    Klarum Purum - KL/KL/CH +Mod
    Leib der Wogen - MU/KL/GE
    Leib des Eises - MU/KL/GE
    Manifesto - KL/IN/CH +Mod
    Memorabia - KL/IN/CH +Mod
    Metamorpho - KL/FF/KK
    Motoricus - KL/FF/KK +Mod
    Nebelwand und Morgendunst - KL/FF/KO
    Objectovoco - KL/IN/CH
    Penetrizzel - KL/KL/KO
    Pestilenz erspüren - KL/IN/CH +Stufe
    Pfeil des [Elements] - KL/IN/CH
    Psychostabilis - MU/KL/KO
    Ruhe Körper, Ruhe Geist - KL/CH/KO
    Seidenzunge - KL/IN/CH +MR
    Sensibar - KL/IN/CH +MR
    Silentium - KL/IN/CH
    Somnigravis - KL/CH/CH +MR
    Unberührt von Satinav - KL/FF/KO +Mod
    Verständigung stören - KL/KL/IN +MR
    Visibili - KL/IN/GE
    Wasseratem - MU/KL/KO
    Weiße Mähn’ und Gold’ner Huf - KL/IN/CH
    Windstille - KL/CH/KK +Mod
    Zauberklinge - KL/FF/KO
```

Das gleiche würde ich für kristallomantische tun.

Ich würde den Code für die betroffenen Zauber wie folgt ändern und dann einen pull request in der "dev" branch stellen.
Da ich nicht so erfahren bin würde ich dich bitten, hier kurz über den code zu schauen bevor ich ihn > 50 mal anpasse :-D

```
<input class="talent-zauber-abvenenum default-hide" type="checkbox" name="attr_zauber_abvenenum" value="1">
<div class="zauber">
    <button type="action" name="act_z_abvenenum-action" class="default-hide"></button>
    <input type="hidden" name="attr_z_abvenenum_action" value="">
    <div class="talent-cell talent-name">
        <button type="roll" name="roll_z_abvenenum" value="@{z_abvenenum_action}"> <span>Abvenenum Reine Speise</span></button>
    </div>
    <div class="talent-cell talent-eigenschaften">
        <select name="attr_Eigenschaft1abvenenum" class="talent-eigenschaft">
            <option value="@{KL}" selected="selected">KL</option>
            <option value="@{IN}">IN</option>
        </select>/
        <select name="attr_Eigenschaft2abvenenum" class="talent-eigenschaft">
            <option value="@{KL}" selected="selected">KL</option>
            <option value="@{IN}">IN</option>
        </select>/
        <select name="attr_Eigenschaft3abvenenum" class="talent-eigenschaft">
            <option value="@{FF}" selected="selected">FF</option>
        </select> + <span class="abbr" title="Modifikator abhängig von Giftstufe, Krankheit und Genießbarkeit (frisch, verdorben)">Mod.</span>
    </div>
    <input type="text" class="talent-spez" name="attr_Spez_abvenenum">
    <input type="number" class="talent-taw" name="attr_ZfW_abvenenum" min="0" value="0">
    <div class="talent-cell talent-taw">11</div>
    <button name="AbvenenumSpez" type="roll" value="@{gm_roll_opt} &{template:DSA-Zauber} {{name=Abvenenum Reine Speise (@{spez_abvenenum})}} {{mod=[[?{Erleichterung (−) oder Erschwernis (+)|0}d1cs0cf2]]}} {{taw=[[@{ZfW_abvenenum} + 2]]}} {{stat1=[[@{Eigenschaft1abvenenum}]]}} {{stat2=[[@{Eigenschaft2abvenenum}]]}} {{stat3=[[@{Eigenschaft3abvenenum}]]}} {{Talent=[[ { [[{0d1 + @{ZfW_abvenenum} + 2 - (?{Erleichterung (−) oder Erschwernis (+)|0}), 0d1}kh1]] - {1d20cs1cf20 + [[{0d1 + (?{Erleichterung (−) oder Erschwernis (+)|0}) - (@{ZfW_abvenenum} + 2), 0d1}kh1]] - @{Eigenschaft1abvenenum}, 0d1}kh1 - {1d20cs1cf20 + [[{0d1 + (?{Erleichterung (−) oder Erschwernis (+)|0}) - (@{ZfW_abvenenum} + 2), 0d1}kh1]] - @{Eigenschaft2abvenenum}, 0d1}kh1 - {1d20cs1cf20 + [[{0d1 + (?{Erleichterung (−) oder Erschwernis (+)|0}) - (@{ZfW_abvenenum} + 2), 0d1}kh1]] - @{Eigenschaft3abvenenum}, 0d1}kh1, 0d1 + @{ZfW_abvenenum} + 2}dh1]]}}">Spez</button>
    <br>
</div>

```


Viele Grüße

**Comment by kreuvf** [comment]
Erst mal vielen Dank für deine Mühen, ich weiß das sehr zu schätzen und bin überrascht, dass die Aufteilung nicht nur mir hilft! :)

Aufgrund der sehr begrenzten Zeit, die ich habe, um mich um den Charakterbogen zu kümmern, versuche ich stets Dinge so einzubauen, dass sie ein Problem möglichst umfänglich lösen. Das ist auch der Knackpunkt an deiner Lösung (weiter unten habe ich meine bevorzugte Lösung des Problems "Zauber in unterschiedlichen Repräsentationen inkl. Ersetzung von Eigenschaften" ausgeführt).

Lass dich davon bitte nicht entmutigen :pensive:, das Ziel ist es zukünftigen Bearbeitern die Arbeit leichter zu machen. Korrigiere mich, falls ich etwas falsch verstanden haben sollte ^.^

Der große Vorteil deiner Lösung ist die Einfachheit, mit der er sich in den bestehenden Code einfügt. Zwei große Nachteile fallen mir aber direkt ins Auge:

* Haufenweise neue Attribute: Für jeden Zauber werden drei neue Attribute benötigt. Das lässt sich natürlich relativ leicht automatisieren, aber aktuell sind die gesamten Zauberdaten in einer einmalig pro Öffnen des Charakterbogens definierten Datenstruktur gespeichert (`const spellsData` in `js/constants.js`). Wie du auch siehst, sind sämtliche Attribute bereits programmatisch erreichbar.
* Beschränkung auf eine Vorauswahl von Zaubern: Der Charakterbogen muss in der Lage sein, für eine möglichst breite Spielerbasis zu funktionieren. Daher ist die Begrenzung auf eine Zauberauswahl ein Garant dafür, dass Issues eröffnet werden mit der Bitte doch Zauber XYZ ebenfalls noch aufzunehmen.

Ein weiterer kleinerer Nachteil ist, dass ein Charakter auf genau eine Repräsentation festgelegt wird, dabei gibt es aber durchaus spielbare Professionen wie den Belhankaer Bewegungsmagier, der von Haus aus Sprüche in elfischer Repräsentation erlernt, oder andere, die eine zweite Repräsentation mit relativ geringem Aufwand erlernen könnten. Daher ist mein Vorschlag für die Übergangslösung die folgende:

* Zu jedem Zauber gibt es ein neues Attribut `attr_z_<zauber>_rep`, das ich zwischen die Spalten "Eigenschaften" und "Spezialisierung" packen würde. Das wird ein Dropdown-Menü, das im Ausgangszustand auf "---" steht. Wenn die Hauptrepräsentation des erste Mal gewählt wird, also die Repräsentation der Zauber noch auf "---" steht, werden alle (ALLE, auch die ausgeblendeten) auf diese Repräsentation gesetzt. Wenn da jemand einen Fehler macht, muss er zur Not halt händisch bei den einzelnen Zaubern ändern, aber so oft sollte das auch nicht vorkommen.
* Beim Zaubern läuft das Ganze ja ohnehin durchs Custom Roll Parsing (Spezialisierungen lassen wir jetzt mal außer Acht~). Das Ganze sollte dann so laufen:
  * Repräsentation anschauen: Repräsentation mit Ersetzungsmöglichkeiten? Falls nein, normal weiter.
  * Falls ja: Eigenschaften der Probe anschauen und prüfen, ob im konkreten Fall Ersetzungsmöglichkeit gegeben. Falls nein, normal weiter.
  * Falls ja: Ersetzbare Probeneigenschaft(en) vergleichen mit ersetzenden Charaktereigenschaften. Wenn ersetzende Charaktereigenschaften besser, automatisch ersetzen und entsprechenden Wert verwenden. Wenn gleich oder schlechter, weiter wie normal.
  * Gegebenenfalls kleine Info ausgeben, dass eine solche Ersetzung durchgeführt wurde.

Der Nachteil daran wäre weiterhin, dass man einen Spruch nur einmal erlernen kann und sich auf eine Repräsentation festlegen muss. Vorteile daran wären:

* Die Ersetzungslogik ist dann bereits in Code gegossen und kann später wiederverwendet werden.
* Alle Zauber werden in jeder Repräsentation ermöglicht.

Wie siehst du das? Wenn du mit irgendwas Probleme hast, kann ich auch gern helfen.

**Comment by Triqueon** [comment]
Wie @kreuvf schon in #136 anmerkt, habe ich ohne zu sehen dass sich hier in letzter Zeit was getan hat eine Umsetzung für zumindest die Elfen eingereicht die recht viel mit seiner vorgeschlagenen Lösung gemeinsam hat. Ich würde die um die beiden anderen Repräsentationen und die Dropdowns an den einzelnen Zaubern erweitern, dann sollte das alles hier besprochene abdecken.

**Comment by Triqueon** [comment]
Oh, und kann mir jemand die konkrete Regel zu den Kophtanim sagen? Bis zu einmal KL durch CH ersetzen oder ist das ausladender? DDZ hab ich leider nicht und würde mir das ungern nur um das zu klären zulegen.

**Comment by kreuvf** [comment]
Nur zur Info: Ich bin aktuell bis Mitte April leider sehr eingespannt. Ich hoffe, ihr könnt die entsprechende Geduld mit mir aufbringen. (Es freut mich sehr, dass hier die letzten Wochen so viel los ist, auch wenn der Zeitpunkt denkbar ungünstig ist xD)

**Comment by kreuvf** [comment]
Elfische Zauber werden, wie auch kristallomantische und kophtanische, mit der kommenden Version insofern unterstützt, dass automatisch Eigenschaften so ersetzt werden, dass das günstigere Ergebnis verwendet wird.

**Comment by adrianbens** [comment]
@kreuvf Erstmal Vielen Dank für dieses tolle neue Feature! Super umgesetzt (auch mit der Anzeige der Ersetzung).
Wollte es direkt ausprobieren, bei zwei (meiner) Zauber (FlimFlam und Ruhe Körper) scheint es nicht zu klappen, bin nicht sicher, ob ich was falsch gemacht habe oder ob es ein Bug ist. 
![ScreenshotRoll20](https://github.com/kreuvf/roll20-character-sheets/assets/98403677/0a99797b-cdff-4301-94b8-0b12c16bf5ee)

**Comment by adrianbens** [comment]
Ok direkt eine Ergänzung, nach etwas ausgiebigeren Tests mit Mitspielern: Wenn man oben die Repräsentation wählt klappt es, wenn man aber an den EINZELNEN Zaubern die Repr. Elf wählt klappt es bei diesen beiden Zaubern NICHT. Also klingt nach einem Bug?

**Comment by kreuvf** [comment]
Bitte in #145 weiterdiskutieren. :)
