### ISSUE TITLE
Korrekte eBE Berechnung für Talente und Kampf

### ISSUE THREAD

**Issue by Koizumi85** [kreuvf/roll20-character-sheets#39]
Derzeit wird die BE bei Kampfaktionen gar nicht in Betracht gezogen, bei Talenten nur die gBE ohne bspw. Rüstungsgewöhnung oder ähnliches. Möglicher Lösungsansatz:

- Bei Rüstungstabelle einen zusätzlichen Haken "Rüstungsgewöhnung I?" hinzufügen
- BE der Rüstung mittels Sheet-Worker unter Einbeziehung von Rüstungsgewöhnung berechnen und in entsprechendes Attribut eintragen
- Bei TaW-Würfen diesen Wert verwenden
- Bei Kampf-Talenten Formeln für eBE hinterlegen (bspw. BE-3 oder sowas) und diese bei der Berechnung der effektiven AT und PA Werte mit einbeziehen

**Comment by kreuvf** [comment]
Ist prinzipiell schon in der [Roadmap](https://github.com/kreuvf/roll20-character-sheets/issues/20#issuecomment-346698459) drin eBE insgesamt mal irgendwie richtig zu machen xD

**Comment by Koizumi85** [comment]
Ich hab da mal was gebastelt. Siehe die letzten beiden Commits in meinem Repo (Auch wenn es nicht in der Commit-Beschreibung enthalten ist. Hab irgendwie gedacht dass es in dem Commit vorher schon drin steht.
Änderungen:
- Man kann bei den Rüstungen genau eine auswählen für die die RG1 aktiv ist
- Die gBE der Rüstung wird entsprechend korrekt berechnet
- Darauf aufbauend wird der BE_TaW berechnet, der sowohl für die Talente als auch für den Kampf als Basis dient
- Aufbauend auf dem BE_TaW und dem, bei der aktiven Waffe, ausgewählten Waffentalent werden die pa- und at-Modifikatoren berechnet
- Diese werden auf die AT und PA Werte der aktiven Waffe angerechnet und dann die finalen Werte entsprechend im Nahkampf-Tab angezeigt

Wo die BE noch nicht eingerechnet wird ist beim Fernkampf. Aber das sollte kein großes Problem sein denke Ich.

Ansonsten finde Ich die Art und Weise wie Ich die Migrationen umgesetzt habe wirklich gelungen.
