### ISSUE TITLE
"BE" does not affect ability checks

### ISSUE THREAD

**Issue by YuanRamirez** [kreuvf/roll20-character-sheets#4]
"Behinderung" (BE) is not taken into consideration when rolling any ability checks either. Although, maybe the player is supposed to enter the modifier for that into the input-value dialog manually?

**Comment by kreuvf** [comment]
Zur Zeit ist es tatsächlich so gedacht, dass der Spieler das selbst einträgt. Das liegt auch daran, dass die tatsächliche BE momentan nicht korrekt ermittelt werden kann. Die BE errechnet sich zum einen aus der Rüstung (und entsprechenden Sonderfertigkeiten) als auch aus der Last, die sich aus dem Inventar ergibt.

Ich lasse das Issue offen, aber eine hohe Priorität hat das momentan nicht, da sehr viel daran hängt, was zuvor in Ordnung gebracht werden muss.

**Comment by YuanRamirez** [comment]
Ahja, ich hatte irgendwo das auch schon gelesen, dass das im Moment noch etwas schwierig ist mit der Kampf-Abteilung des Character Sheets. Wenn das mit der Behinderung nur schwer ermittelt werden kann, dann merk ich mir das und sag beim nächsten Mal der Spielgruppe Bescheid, dass wir da selber drauf achten müssen (muss man ja mit Stift und Papier auch)

**Comment by kreuvf** [comment]
@YuanRamirez Ich habe vor mich die kommende Woche ein wenig um die BE zu kümmern. Konkret steht folgendes auf dem Plan:
* BE aus Last einbeziehen
  * manuell (BE eintragen)
  * automatisch (Last eintragen; Vorteil: bei KK-(De)buff automatische Neuberechnung der BE)
* BE bei Proben einbeziehen
  * genaue Umsetzung noch nicht sicher
  * Aber: eBE wird auf jeden Fall automatisch ausgerechnet und einberechnet

Solange das Inventar nicht steht, müssen die Spieler ihre Last noch selbst eintragen. Danach (kA, wann :P) werde ich dann wohl drei Optionen anbieten: manuell, semiautomatisch (Last manuell eintragen), vollautomatisch (Last aus Inventar).

**Comment by kreuvf** [comment]
So, nach einigem Herumprobieren bin ich zu der Überzeugung gelangt, dass ich die Sache mit der BE erst zu einem späteren Zeitpunkt abschließen können werde. Ich werde das auf eine sehr manuelle Art und Weise einbauen, aber dann später mit Sheet Worker Scripts nochmal deutlich besser machen.

Die Umsetzung sieht wie folgt aus:
* BE aus Last nur manuell einbeziehen
* Angabe für eBE wird Würfelbutton mit voreingestelltem Modifikator gemäß eBE, der durch den Nutzer änderbar ist. Zusätzlich wird nach dem normalen Probenmodifikator gefragt.

**Comment by kreuvf** [comment]
So, die tatsächliche Umsetzung ließ sich (noch?) nicht so machen wie ich das gern gehabt hätte, daher habe ich mich dazu entschlossen, dass der Button keine Wahl für die eBE lässt, dafür wird diese aber angezeigt im Roll Template, sodass Modifikator und eBE erscheinen.
