### ISSUE TITLE
Migrationen ohne böse Überraschungen

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#41]
Grundsätzlich ist eine Migration alter Charakterbögen auf neue Versionen problemlos denkbar. Doch macht eine Eigenheit der Funktionen `getAttrs()` und `setAttrs()` dem Ganzen einen Strich durch die Rechnung: Asynchronität.

Die Lösung die verschiedenen Migrationsfunktionen über eine Schleife nacheinander durchlaufen zu lassen, führt auf kurz oder lang zu race conditions und/oder inkonsistenten Daten, weil beide Funktionen asynchron sind. Solche Bugs lassen sich quasi nicht reproduzieren und können Spielern den Charakterbogen zerschießen.

Die aktuell von mir favorisierte Lösung ist wenig anwenderfreundlich:

1. Beim Öffnen des Sheets wird geprüft, ob mehr als eine Migration nötig wird. Ist dies der Fall, weiter beim nächsten Schritt, sonst die bis zu eine Migration durchführen. Ist der Bogen gesperrt, wird er entsperrt.
1. Der Charakterbogen wird "gesperrt", indem via CSS eine entsprechende Meldung ein- und der restliche Teil des Bogens ausgeblendet wird. Ist der Bogen bereits gesperrt, wird die Nachricht aktualisiert.
1. Die erste/nächste Migration wird durchgeführt. Der Spieler wird in der Mitteilung dazu aufgefordert den Charakterbogen zu schließen und erneut zu öffnen.

In der Hoffnung, dass vor dem Schließen des Charakterbogens kein Code unausgeführt bleibt, sollte beim erneuten Öffnen stets ein konsistenter Zustand herrschen. Die einzige Alternative dazu, die mir einfällt, ist eine immer größer werdende Migrationsfunktion, die für sämtliche Ausgangsversionen korrekt migriert. Dass das aber bereits nach fünf Versionen kaum mehr wartbar und den Aufwand wert ist, ist hoffentlich leicht einzusehen.

Falls jemand bessere Ideen hat, diese Updates umzusetzen, nur her damit. Möglicherweise verstehe ich auch nur asynchrone Funktionen in JavaScript nicht ausreichend, um zu erkennen, dass ich mir da unnötige Sorgen mache.

**Comment by Koizumi85** [comment]
Der Plan den Ich versuchen werde:
Jede Migration ruft in der callback-Function für das setAttrs die jeweils nächste Migration auf. Allerdings muss Ich dafür auch die Migration für die Gaben/Metatalente überarbeiten, da dort mehrere setAttrs aufgerufen werden. Ich glaube allerdings, dass diese Methode derzeit auch mit Race-Conditions zu kämpfen hat, weshalb wir da sowieso nochmal dran gehen sollten. :)

**Comment by Koizumi85** [comment]
@kreuvf schau dir mal den Commit hier an. Der sollte die Probleme hoffentlich lösen: https://github.com/Koizumi85/roll20-character-sheets/commit/c83d18e15c2034f164b6f5e0b2cee13399c83446

**Comment by kreuvf** [comment]
> Der Plan den Ich versuchen werde:
> Jede Migration ruft in der callback-Function für das setAttrs die jeweils nächste Migration auf. Allerdings muss Ich dafür auch die Migration für die Gaben/Metatalente überarbeiten, da dort mehrere setAttrs aufgerufen werden. Ich glaube allerdings, dass diese Methode derzeit auch mit Race-Conditions zu kämpfen hat, weshalb wir da sowieso nochmal dran gehen sollten. :)

Das ist zwar [nicht performant und es wird auch explizit davor gewarnt das zu tun](https://roll20.zendesk.com/hc/en-us/articles/360037773513-Sheet-Worker-Scripts), aber ich denke, dass man das an dieser Stelle ruhig tun kann. Spielt jemand mindestens einmal im Monat mit dem Bogen, wird er kaum mehr als zwei Migrationen benötigen. Die Gesamtladezeit des Bogens ist im Vergleich zur Laufzeit der Migrationsfunktionen immer noch um ein Vielfaches länger - Bloat halt. Wer lange (Jahre) nicht mit dem Bogen gespielt hat, wird etwas warten müssen und sich im Zweifel sowieso darüber aufregen, dass **jetzt auf einmal plötzlich und ohne den Nutzer vorher um Erlaubnis gebeten zu haben _alles_** total anders sei ;)

**Comment by Koizumi85** [comment]
Ja, die Warnung habe Ich prinzipiell auch gesehen aber Ich denke es ist hier bei weitem die einfachste Möglichkeit. Performance ist tatsächlich absolut kein Problem. Die beiden Migrationen die jetzt drin sind (und die sind schon ziemlich groß geworden), laufen innerhalb von (geschätzt) 50 Millisekunden durch. Das merkt man also noch nicht mal...
Und es ist auf jeden Fall besser als nem Benutzer zu sagen er solle das Sheet einmal zu machen und neu Öffnen. Das könnte manche überfordern ;)

**Comment by kreuvf** [comment]
Ich habe es gerade mal mit einem Testsheet (214d104) getestet: Das Update der Gaben und Metatalente funktioniert noch so wie es soll :)

**Comment by Koizumi85** [comment]
Super. Das freut mich. Alle meine Migrationen funktionieren ebenfalls noch so wie Sie es tun sollen. Ich denke dann kann man das Ticket hier schließen, oder?

**Comment by kreuvf** [comment]
Bitte in der Commitnachricht "Closes kreuvf/roll20-character-sheets#41" zum Schließen reinschreiben. Dann wird es von allein geschlossen, wenn der PR bei Roll20 durch ist und ich meinen Fork aktualisiere. Falls du willst, kannst du dich im Übrigen auch noch in den Footer des Sheets setzen, wo auch alle anderen Autoren schon stehen xD

**Comment by Koizumi85** [comment]
Okay. Ich habe gerade meine Commit-Nachrichten angepasst (Daher werden die alten Links zu den Commits nicht mehr funktionieren). Ich werde mich dann jetzt daran machen den Stand so wie er derzeit ist als PR an Roll20 aufzusetzen.

**Comment by kreuvf** [comment]
Kannst du das auch als PR gegen mein Repo machen, damit ich nochmal (größtenteils kosmetische) Änderungen vornehmen kann?

**Comment by Koizumi85** [comment]
done. Hast du gerade noch rechtzeitig geschrieben :D

**Comment by kreuvf** [comment]
So, ich habe mir auch den Migrationscode zu Gemüte geführt und bin dabei über eine Sache gestolpert: `data_version`.

Roll20 hat die sinnvolle Einstellung, dass ein Attribut, das vom Sheet vorgegeben wird, aber nie geändert, sprich: mit `setAttrs()` oder vom Spieler gesetzt wurde, bei Updates des Sheets automatisch mitaktualisiert wird.

Das Attribut `data_version` ist jetzt seit fast drei Jahren gleich. Das ist ziemlich dämlich, denn ein neuer Charakter ist ja bereits auf der aktuellen Version, darf aber beim ersten Aufmachen dennoch alle Migrationsfunktionen durchlaufen, auch wenn das unnötig ist/sein sollte. Wenn ich jetzt aber `data_version` gleichsetze mit `character_sheet_version`, würden all jene Sheets keine Updates bekommen, die seit ~3 Jahren ungeöffnet sind.

Was hälst du von der folgenden Idee: `data_version` ist ein standardmäßig leeres Attribut. Beim Öffnen des Bogens wird dann folgendes gemacht: Ist `data_version` leer, muss es sich um ein neues Sheet handeln. Migrationen sind dann keine nötig. Gibt es ein Sheet-Update, so verändert sich die `character_sheet_version`, die `data_version` ist noch auf einem alten Stand. Das wird erkannt und die entsprechenden Migrationen aufgerufen. Hätte man von Anfang an so machen sollen :P

Siehst du damit irgendwelche Probleme oder kann ich das so machen? Dann würde ich die `data_version` nämlich direkt mit dem kommenden PR leeren (etc. pp.), sodass das künftig so funktionieren kann.

**Comment by Koizumi85** [comment]
Kannst du nicht in der sheet.json default-values einstellen? Wenn du dort die data_version auf die aktuelle Version einstellen würdest, dann sollte die für einen neuen Charakter automatisch gesetzt sein, aber für bestehende Charaktere nicht automatisch überschrieben werden. Dann brauchen wir glaube Ich nichts weiter anzupassen, oder?

**Comment by kreuvf** [comment]
[Default Sheet Settings](https://roll20.zendesk.com/hc/en-us/articles/360041542554-Default-Sheet-Settings) sieht mir nicht nach etwas aus, das die Situation ändern würde ^^

Die Änderung wäre ja auch gar nicht groß: `data_version` wird leer/undefined initialisiert und in den Migrationen gesetzt, wenn sie nicht gesetzt ist. Denn leere `data_version` bedeutet: Dieses Attribut wurde noch nicht gesetzt. Da der Bogen dann aber immer das Attribut setzt, erlaubt uns das zuverlässig zu unterscheiden, ob das ein neuer Bogen ist (keine Migration nötig), eine alte Version (Migration nötig) oder die Version aktuell ist (keine Migration nötig). Meine Frage ist aber eben, ob du da Logikfehler drin erkennst oder nicht xD

**Comment by Koizumi85** [comment]
Ne. Das passt schon so. Dachte nur mit den Default settings würde das gehen

Kreuvf <notifications@github.com> schrieb am So., 16. Aug. 2020, 11:37:

**Comment by kreuvf** [comment]
14f566c3175ed517274bb1e71ecca6b798f88479 ist fertig und funktioniert in meinen Tests genauso wie es soll :)

**Comment by Koizumi85** [comment]
Joa. Sieht gut aus :)
