### ISSUE TITLE
Kampf: Schildangriff nicht implementiert

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#42]
Nachdem via Issue #23 über die Zeit tatsächlich Schilde und Parierwaffen in den Bogen Einzug gehalten haben, fehlt der Schildangriff weiterhin. Quellen dafür sind WdS, S. 63 und S. 76.

Hier hat sich die Redaktion wieder mal etwas besonders Vertracktes ausgedacht:

* Prinzipiell ist der Schildangriff eine Raufen-AT +3 und Schildkampf I wird benötigt.
* Die Erschwernis entfällt aber, sofern eine der folgenden Bedingungen erfüllt ist:
  * Der Kämpfer verfügt über Schildkampf II
  * Der Kämpfer verfügt über das waffenlose Manöver Knaufschlag
  * Der Kämpfer verfügt über das waffenlose Manöver Schmutzige Tricks (was auch immer an einem Schildangriff ein schmutziger Trick sein soll ...)
* Die Raufen-AT ist zusätzlich um den AT-WM des Schildes erschwert (also ... da der ja in der Regel negativ ist, müsste das eine Erleichterung ergeben ... ist also vermutlich der Betrag des AT-WM :nerd_face:)
* Weil das noch nicht komplex genug ist, darf man wie bei einem Wuchtschlag zusätzlich ansagen - das Ansagemaximum orientiert sich dabei vermutlich auch am Raufen-AT. Die SF Wuchtschlag wird wohl nicht benötigt, d. h. ohne kriegt man pro 2 Ansage 1 TP mehr.
* Weil das auch noch nicht komplex genug ist, darf man mit dem Schild einen Angriff zum Niederwerfen durchführen, wobei die SF bekannt sein muss. Gemäß den Niederwerfenregeln ist auch hier noch eine Ansage aus dem Wuchtschlag möglich ... und Niederwerfen kann mit einem Sturmangriff kombiniert werden!
* Schilde richten dann TP(A), wobei sowohl die als auch die TP/KK erst mal auf einem Standardwert liegen.
* Immerhin noch als Hinweis ins Roll Template aufnehmbar: Dolche, Fecht- und Kettenwaffen können Schildangriffe nicht parieren, AUSSER wenn sie mit einem Buckler oder Bock durchgeführt werden.

**Comment by Koizumi85** [comment]
Ja... die Regeln für den Schildangriff sind sowas von total Banane... Keine Ahnung was sich die Autoren dabei gedacht haben... 🤷‍♂️

**Comment by Koizumi85** [comment]
So. Hab mir das jetzt mal bisschen durch den Kopf gehen lassen was davon für das Sheet prinzipiell relevant ist und was nicht, bzw. wie man vorgehen kann:

- Hat der Char ein aktives Schild und Schildkampf I aktiviert, dann ist die Schild-Attacke als Roll-Button verfügbar
- AT-Wert für Schild-Attacke wird einfach als Raufen-AT mit den entsprechenden Modifikatoren als eigenes Attribut berechnet (also wie bspw. die Schildparade)
- Die "Wuchtschlag" Option würde Ich erstmal außen vor lassen. Das kann man ja erstmal mittels des normalen "Ansage"-Buttons erledigen
- Niederwerfen würde Ich als eigenen Roll-Button "Niederwerfen (Schild)" 
- Die Kombination Niederwerfen (Schild) + Sturmangriff kann man einfach als Niederwerfen (Schild) + 4 würfeln. Müssen wir also auch nicht zwingend aufnehmen
- Trefferpunkte für den Schildschlag müsste man dann als eigenen Roll-Button hinterlegen. Könnte man aber auch erstmal weglassen und die Spieler würfeln Sie erstmal mit nem normalen W6 aus

Ich setz mich da auf jeden Fall die Tage mal dran.

**Comment by kreuvf** [comment]
> So. Hab mir das jetzt mal bisschen durch den Kopf gehen lassen was davon für das Sheet prinzipiell relevant ist und was nicht, bzw. wie man vorgehen kann:
> 
> * Hat der Char ein aktives Schild und Schildkampf I aktiviert, dann ist die Schild-Attacke als Roll-Button verfügbar

Da drängt sich mir doch glatt die Frage auf, ob man mit einem Schildangriff auch einen Passierschlag ausführen kann ... ;D

> * AT-Wert für Schild-Attacke wird einfach als Raufen-AT mit den entsprechenden Modifikatoren als eigenes Attribut berechnet (also wie bspw. die Schildparade)

Dafür.

> * Die "Wuchtschlag" Option würde Ich erstmal außen vor lassen. Das kann man ja erstmal mittels des normalen "Ansage"-Buttons erledigen

Dafür. Kann man immer noch später einbauen.

> * Niederwerfen würde Ich als eigenen Roll-Button "Niederwerfen (Schild)"

Dafür.

> * Die Kombination Niederwerfen (Schild) + Sturmangriff kann man einfach als Niederwerfen (Schild) + 4 würfeln. Müssen wir also auch nicht zwingend aufnehmen

Dafür. Kann man immer noch später einbauen.

> * Trefferpunkte für den Schildschlag müsste man dann als eigenen Roll-Button hinterlegen. Könnte man aber auch erstmal weglassen und die Spieler würfeln Sie erstmal mit nem normalen W6 aus

Oder eigenen Kasten für Schildangriff/Schildparade, dann hat man das auch optisch getrennt.

**Comment by Koizumi85** [comment]
> Da drängt sich mir doch glatt die Frage auf, ob man mit einem Schildangriff auch einen Passierschlag ausführen kann ... ;D

ne. Das geht auf jeden Fall nicht. Ein Passierschlag kann nur mit der Hauptwaffe ausgeführt werden :-D

> Oder eigenen Kasten für Schildangriff/Schildparade, dann hat man das auch optisch getrennt.

Hört sich gut an

**Comment by Koizumi85** [comment]
@kreuvf Hab den Schildangriff jetzt auch soweit fertig. Muss nur noch bisschen Aufräumarbeiten am Code machen.
Da wir ja einen neuen Kasten für die Schild-Angriffe/Paraden machen wollen, habe Ich das jetzt grade mal alles auf das Grid-Layout umgebaut. Das macht den ganzen Code etwas schlanker (man spart sich die ganzen <tr></tr> Zeilen) und ist - wenn man sich mal dran gewöhnt hat auch einfacher zu stylen.
Habe in dem Zug auch die Labels in den Kästen geändert. Ich fand diese verwirrend (Über der zweiten Spalte stand "Proben" obwohl es ja eigentlich Erleichterung/Erschwernis Proben waren). Habe da jetzt einfach einzelne Labels für die entsprechenden Abschnitte rein geschrieben weil die Buttons für sich deutlich genug aussagen was Sie tun.
Ich finde der passt in dem Format optisch da nirgends wirklich rein. Ist die Frage ob man das nicht so macht wie im Heldenbogen bzw. bei der Eingabe der Rüstungen dass man einfach eine Tabelle mit Header und einer Zeile hat wo die Gesamtwerte alle nebeneinander drin stehen.

So sieht es jetzt im Moment aus.
![image](https://user-images.githubusercontent.com/7482685/90314924-aa24c600-df17-11ea-9cad-9b27e6b0fdac.png)

**Comment by Koizumi85** [comment]
Arbeit zu finden hier: https://github.com/Koizumi85/roll20-character-sheets/tree/dsa4.1-shield-attack

**Comment by kreuvf** [comment]
Habe es jetzt endlich mal getestet und ich kann nach einem Kurztest sagen, dass es immerhin grundsätzlich funktioniert. Mal gucken, wann ich das in der Tiefe teste (und darauf herumhämmere, bis es in Trümmern liegt xD).

**Comment by kreuvf** [comment]
Folgende Punkte sind mit aufgefallen:

- SK1: Schildangriff ist Attacke +3 (nicht: Attacke ±0 mit AT-Wert -3); hatte ich ursprünglich missverstanden ...
- AT-WM des Schildes: Wirkt als Erschwernis auf Attacke (nicht: AT-Wert - AT-WM des Schildes); hatte ich ursprünglich missverstanden ...
- Wuchtschlag sollte sich leicht via eigenen Button einbauen lassen
- Niederwerfen sollte sich ebenfalls leicht via eigenen Button einbauen lassen

Der Code sieht so weit solide aus, ich werde aber noch ein bisschen daran herumfummeln :)

**Comment by kreuvf** [comment]
Wuchtschlag ließ sich tatsächlich vergleichsweise einfach einbauen :) Die Modifikatoren aus dem Schildangriff (+3/±0 bei SFen, Schild-AT-WM) sind mit drin und auch die Ansage aus dem Wuchtschlag, ob mit oder ohne Sonderfertigkeit.

**Comment by kreuvf** [comment]
Niederwerfen ist nun auch drin. :)

**Comment by kreuvf** [comment]
Es braucht noch einen Weg, um die Trefferpunkte aus der Schildattacke auszurechnen. TP/KK für Schilde ist ja vorhanden, sollte also auch mit ein wenig Copy & Paste machbar sein.

**Comment by kreuvf** [comment]
So, Trefferpunkte können nun auch korrekt gewürfelt werden :D

**Comment by kreuvf** [comment]
Jetzt kann das Trefferpunkte-Rolltemplate unterscheiden zwischen TP und TP(A). Im nächsten Schritt brauche ich mir dann nur noch die Tabelle mit den Rüstungswerten anzuschauen und gegebenenfalls anzupassen. :D

**Comment by kreuvf** [comment]
Mir ist da gerade eine Idee gekommen: Buttons für jedes Körperteil. Wenn man den Knopf dann drückt, gibt man nur TP oder TP(A) und den Wert an, dann werden SP oder SP(A) ausgerechnet, aus technischen Gründen aber nicht automatisch von der LE/AU abgezogen.

**Comment by kreuvf** [comment]
Für den Anfang belasse ich es bei der Grundfunktionalität, alles weitere kommt dann in #63.

**Comment by kreuvf** [comment]
Bis auf die Updatefunktion steht soweit alles. Das Design des Nahkampf-Tabs ist irgendwann mal zur Generalüberholung dran.

![image](https://user-images.githubusercontent.com/518136/111914474-62988680-8a72-11eb-9441-d239c8c24105.png)

**Comment by kreuvf** [comment]
Updatefunktion hierfür steht dann auch. :D
