### ISSUE TITLE
Initiative: Waffenmodifikator berücksichtigen

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#46]
Quelle: https://www.youtube.com/watch?v=a6KadwTIcQY&lc=UgxZvWSc0AGtn7qZ20l4AaABAg

Offenbar wird der INI-Modifikator der Waffe (des Schildes und der Parierwaffe xD) beim INI-Wurf nicht berücksichtigt. Den INI-Wurf müsste man ohnehin nochmal komplett überarbeite, da der User nicht wählen muss, wie viele W6 er würfeln darf. Das kann man von den entsprechenden Sonderfertigkeiten abhängig machen.

**Comment by Baguron** [comment]
Wäre toll. Aber die Würfel ob 1w6 oder 2w6 sind wählbar.

**Comment by kreuvf** [comment]
> Aber die Würfel ob 1w6 oder 2w6 sind wählbar.

Ich weiß ;) Das braucht es aber nicht, da der Spieler nicht wählen kann. Entweder die Sonderfertigkeit ist aktiv, dann sind es 2W6, oder die Sonderfertigkeit ist inaktiv/nicht vorhanden, dann ist es nur 1W6.

**Comment by Baguron** [comment]
Ich nutze den Bogen auch gerne für Monster etc. da wäre es komisch wenn die die Sonderfertigkeit hätten.

**Comment by kreuvf** [comment]
> Ich nutze den Bogen auch gerne für Monster etc. da wäre es komisch wenn die die Sonderfertigkeit hätten.

Kein Problem, dann würfeln die automatisch mit 1W6. :)

**Comment by Baguron** [comment]
Es gibt auch Monster mit 2w6 Iniwurf

**Comment by kreuvf** [comment]
> Es gibt auch Monster mit 2w6 Iniwurf

Ist notiert.

**Comment by Koizumi85** [comment]
@kreuvf Ich werd mich mal an das Issue hier machen, falls du noch nicht dran bist

**Comment by kreuvf** [comment]
> @kreuvf Ich werd mich mal an das Issue hier machen, falls du noch nicht dran bist

Kannst du machen, bin noch nicht dran.

**Comment by Garonenur** [comment]
Parierwaffen werden berücksichtigt, aber Hauptwaffen nicht, ist das der aktuelle Stand?

**Comment by kreuvf** [comment]
> Parierwaffen werden berücksichtigt, aber Hauptwaffen nicht, ist das der aktuelle Stand?

Ich habe es gerade nochmal getestet: INI-Modifikatoren auf der Hauptwaffe werden nicht angerechnet, auf Schilden und Parierwaffen schon.
