### ISSUE TITLE
Wunden: Modifikatoren berücksichtigen

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#47]
Quelle: https://www.youtube.com/watch?v=a6KadwTIcQY&lc=UgxZvWSc0AGtn7qZ20l4AaABAg

Die Modifikationen von AT, PA, FK und INI durch Wunden werden nicht angerechnet. Prinzipiell bereits bekannt, jetzt aber auch offiziell gewünscht ^_^

**Comment by Koizumi85** [comment]
Sollte man das konfigurierbar machen? Ich kenne Gruppen die für Wunden Ihre eigenen Systeme haben und nicht mit diesen Modifikatoren spielen

**Comment by Baguron** [comment]
Ich fänd das gut.

**Comment by kreuvf** [comment]
> Sollte man das konfigurierbar machen? Ich kenne Gruppen die für Wunden Ihre eigenen Systeme haben und nicht mit diesen Modifikatoren spielen

Solange hier niemand seine Wünsche für Hausregeln dokumentiert, werde ich das nicht berücksichtigen. Ich sehe große Probleme damit, Hausregeln zu unterstützen, da eine Abgrenzung zwischen Kleinigkeiten (kann man problemlos einbauen) und großen Änderungen (schmeißen etliche Teile des Sheets um) fließend ist und damit Hausregeln eher willkürlich eingebaut für eine Aufnahme ins Sheet ausgewählt werden.

**Comment by Koizumi85** [comment]
Es geht mir nicht darum die Hausregeln explizit zu unterstützen Dafür gibt es in diesem Fall wahrscheinlich eh einfach zu viele. Aber meines Wissens ist das Spiel mit Wunden generell eine der als "Optional" gekennzeichneten Regeln und dann fände Ich es angebracht wenn man die automatische Einbeziehung der Modifikatoren auch optional macht. Zumal das ja auch kein großer Mehraufwand in der Umsetzung wäre.

**Comment by kreuvf** [comment]
> Es geht mir nicht darum die Hausregeln explizit zu unterstützen Dafür gibt es in diesem Fall wahrscheinlich eh einfach zu viele. Aber meines Wissens ist das Spiel mit Wunden generell eine der als "Optional" gekennzeichneten Regeln und dann fände Ich es angebracht wenn man die automatische Einbeziehung der Modifikatoren auch optional macht. Zumal das ja auch kein großer Mehraufwand in der Umsetzung wäre.

Der Fernkampfrechner unterstützt das btw bereits indirekt: Bei der Schussart kannst du einen gezielten Schuss wählen (nur Zonensystem) oder den Schuss mit Ansage (nur Gesamtrüstschutzsystem). Wenn man das über eine Option im Sheet macht, könnte man auch hier direkt was verändern, sodass man die Schussart aus dem "falschen" System gar nicht erst sieht. Ich denke daher, dass ein vollständiger Einbau mehr als "kein großer Mehraufwand" ist.

Für's Erste werden die Modifikatoren nach Zonensystem kommen, dann Wunden im Gesamtrüstschutzsystem und dann -- und das würde ich in ein eigenes Issue verlagern -- der Einbau einer sich sheetweit auswirkenden Option.

**Comment by kreuvf** [comment]
Die Auswirkungen von Zonenwunden ohne Sondereffekte bei dritter Wunde (WdS, S. 108):

- Kopf: MU, KL, IN, IB je −2, INI −2W6
- Brust/Rücken: AT, PA, FK, KO, KK je −1, +1W6 SP
- Schwertarm: AT, FK, KK, FF je −2
- Schildarm: PA, FK, KK, FF je −2
- Bauch: AT, PA, FK, KO, KK, GS, IB je −1, +1W6 SP
- Beine: AT, PA, FK, GE, IB je −2, GS −1

Eine Neuberechnung abgeleiteter Werte findet nicht statt. Die GS kann durch Wunden nicht unter 1 fallen.

**Comment by kreuvf** [comment]
> - Schwertarm: AT, FK, KK, FF je −2
> - Schildarm: PA, FK, KK, FF je −2

Dieser Punkt gestaltet sich am schwierigsten. Für dieses Issue hier gehe ich nur von einem Kämpfer mit Schild und Schwert aus. Problematisch wird es nämlich, wenn Spieler mit zweihändigen Waffen kämpfen oder gar kein Schild bzw. keine Parierwaffe führen. Anderthalbhänder, die mitten im Kampf wechseln, sollten dahingegen kein großes Problem darstellen.

Da es grundsätzlich hierfür aber schon ein Issue gibt (#51), werde ich das erst dort versuchen zu beheben. Das wird definitiv eine größere Sache.

**Comment by kreuvf** [comment]
> > * Schwertarm: AT, FK, KK, FF je −2
> > * Schildarm: PA, FK, KK, FF je −2
> 
> Dieser Punkt gestaltet sich am schwierigsten. Für dieses Issue hier gehe ich nur von einem Kämpfer mit Schild und Schwert aus. Problematisch wird es nämlich, wenn Spieler mit zweihändigen Waffen kämpfen oder gar kein Schild bzw. keine Parierwaffe führen. Anderthalbhänder, die mitten im Kampf wechseln, sollten dahingegen kein großes Problem darstellen.

Nach Rücksprache mit meiner Gruppe ist der Fall Schild + Schwert wohl allgemein seltener als nur Waffen-AT/PA (egal ob einhändig oder zweihändig), weshalb das so erweitert wird, dass AT und PA je um 2 vermindert werden.
