### ISSUE TITLE
"Passierschlag" does not apply -4 modifier and does not have a sheet roll

### ISSUE THREAD

**Issue by YuanRamirez** [kreuvf/roll20-character-sheets#5]
"Passierschlag" is not calculated correctly. It should be "Attacke" - 4 but right now it's just the value of "Attacke".

**Comment by kreuvf** [comment]
(If I should write in English, please say so.)

Passierschläge sind besondere Attacken, die standardmäßig eine Erschwernis von 4 nach sich ziehen. Der +/--Wurf hat als Standardwert bereits die "4" drin. Bei Gegnern mit "Aufmerksamkeit" beträgt die Erschwernis 8. Des Weiteren wird noch eine freie Aktion benötigt.

Der Attackewert bleibt dabei stets unverändert, sodass auch auch kein Wert dafür berechnet werden muss - ich sollte also eher die Berechnung entfernen. Regeltechnisch wird der AT-Wert nicht verändert; lediglich der Zielwert, den man maximal erwürfeln darf, ändert sich.

Was hälst du davon, wenn ich den Passierschlag wie folgt abändere (nur auf den Button achten!)?
![Passierschlagbutton](https://cloud.githubusercontent.com/assets/518136/23628045/4ca3418a-02b3-11e7-97ee-4004911283ba.png)
Ich möchte sowieso mehr der wenig aussagekräftigen, dafür aber Platz fressenden Würfelbuttons durch ordentlich beschriftete Buttons ersetzen. Da die Probe bei einem Passierschlag allerdings noch durch andere Dinge erschwert sein kann, bleibt der +/--Button natürlich.

**Comment by YuanRamirez** [comment]
Ahja okay. Das mit dem größeren, beschrifteten Button finde ich gut.
Muss gestehen, dass ich mich auf die Berechnungsanzeige verlassen und nicht weiter ausprobiert hatte, ob der gegebene Würfel-Knopf das richtige macht.

**Comment by kreuvf** [comment]
Kein Problem, denn immerhin ist das nicht gerade leicht zu verstehen, gerade wenn man die alte Version gewöhnt ist. Da das Issue damit erledigt ist, werde ich es schließen.

Die optische Überarbeitung des Kampftabs steht ohnehin auf dem Programm, ist allerdings nicht mal eben schnell gemacht. ^^
