### ISSUE TITLE
INI-Modifikatoren (Kampfreflexe, Waffenboni etc.)

### ISSUE THREAD

**Issue by starsailor78** [kreuvf/roll20-character-sheets#54]
Frohes Neues Jahr!

INI-Modifikationen aus Kampfreflexe und Kampfgespür werden nicht automatisch angerechnet, sondern müssen als Modifikator auf den Grundwert eingetragen werden, richtig?

Weiterhin (habe gerade gesehen, dass das weiter unten bereits notiert wurde:) im DSA4.1-Sheet können INI-Boni (z. B. Säbel +1) oder -Mali (Orknase -1) vermerkt werden. Ist nicht vorgesehen, dass diese in den INI-Wurf eingerechnet werden? (Habe es mit der als aktiv markierten Waffe aus dem Nahkampf-Reiter getestet).

**Comment by kreuvf** [comment]
> INI-Modifikationen aus Kampfreflexe und Kampfgespür werden nicht automatisch angerechnet, sondern müssen als Modifikator auf den Grundwert eingetragen werden, richtig?

Ja, diese SF sind noch nicht eingebaut.

> Weiterhin (habe gerade gesehen, dass das weiter unten bereits notiert wurde:) im DSA4.1-Sheet können INI-Boni (z. B. Säbel +1) oder -Mali (Orknase -1) vermerkt werden. Ist nicht vorgesehen, dass diese in den INI-Wurf eingerechnet werden? (Habe es mit der als aktiv markierten Waffe aus dem Nahkampf-Reiter getestet).

Ist bekannt, siehe Issue #46.

**Comment by kreuvf** [comment]
Klingentänzer wird ebenfalls eingebaut. Die Wirksamkeitsbegrenzung abhängig von der BE (Kampfreflexe nur <= 4, Klingentänzer nur <= 2) könnte kommen, steht aber noch nicht fest.
