### ISSUE TITLE
TP_W_Aktiv und TP_Bonus_Aktiv werden nicht mehr berechnet

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#69]
Quelle: https://www.youtube.com/watch?v=le3ys6T389o&lc=UgwBwIZcm4pgWoR1QfN4AaABAg

Beim Entfernen "toten" Codes sind zwei versteckte auto-calculating fields für diese beiden Attribute entfernt worden, sodass der TP-Würfel-Button für die Nahkampfwaffe nicht mehr funktioniert.

**Comment by kreuvf** [comment]
Um das nochmal in aller Deutlichkeit zu sagen: Dieser Bug war echt dumm von mir. :disappointed: :sob:

**Comment by Bellistor** [comment]
Wir freuen uns auf den Fix... aktuell müssen wir die TP "manuell" auswürfeln - OMG! ^^

**Comment by kreuvf** [comment]
> Wir freuen uns auf den Fix... aktuell müssen wir die TP "manuell" auswürfeln - OMG! ^^

Das ist prinzipiell nicht notwendig! HAbe es schon unter der YouTube-Video gepostet, im Telegram-Kanal und auf Orkenspalter erwähnt:
Abhilfe für TP-Würfel-Bug (vollständige Funktion, aber etwas schwieriger):
1. Charakter öffnen
2. Tab "Attributes & Abilities" öffnen
3. "Add" bei "Attributes" drücken
4. Name (linkes Feld): TP_W_Aktiv
5. Wert (mittleres Feld): @{NKW_Aktiv1} * @{NKWschaden1_1} + @{NKW_Aktiv2} * @{NKWschaden2_1} + @{NKW_Aktiv3} * @{NKWschaden3_1} + @{NKW_Aktiv4} * @{NKWschaden4_1}
6. "Add" bei "Attributes" drücken
7. Name (linkes Feld): TP_Bonus_Aktiv
8. Wert (mittleres Feld): @{NKW_Aktiv1} * (@{NKWschaden1_2} + @{NKW1_SB}) + @{NKW_Aktiv2} * (@{NKWschaden2_2} + @{NKW2_SB}) + @{NKW_Aktiv3} * (@{NKWschaden3_2} + @{NKW3_SB}) + @{NKW_Aktiv4} * (@{NKWschaden4_2} + @{NKW4_SB})

Abhilfe für TP-Würfel-Bug (bei Waffenwechsel händisch anpassen, aber etwas einfacher):
1. Charakter öffnen
2. Tab "Attributes & Abilities" öffnen
3. "Add" bei "Attributes" drücken
4. Name (linkes Feld): TP_W_Aktiv
5. Wert (mittleres Feld): 1 oder 2 (hängt davon ab, wie viele Schadenswürfel eure Waffe hat)
6. "Add" bei "Attributes" drücken
7. Name (linkes Feld): TP_Bonus_Aktiv
8. Wert (mittleres Feld): die Zahl nach dem "+" beim Waffenschaden (also bei Waffe mit 1W6 + 4 kommt hier nur die 4 rein)

Neues Video dazu kommt.

**Comment by bepunkt90** [comment]
Danke für den Workaround, so können wir weiter spielen.
Wird das denn auch in den Vorlagen gefixed? Der Fehler tritt halt auch auf, wenn ich neue Charaktere anlege. Vielen Dank im voraus.
PS: Euer Charakterbogen ist super und er bereitete uns schon viele Stunden spielspaß. Ihr seid toll *thumbsup*

**Comment by kreuvf** [comment]
> Wird das denn auch in den Vorlagen gefixed? Der Fehler tritt halt auch auf, wenn ich neue Charaktere anlege. Vielen Dank im voraus.

Ja, wird es. Momentan liegt es nur an Roll20, die sich Zeit damit lassen, die Fehlerbehebung zu übernehmen. WICHTIG: Wenn ihr den Workaround verwendet, müsst ihr das später wieder rückgängig machen, wenn der Charakterbogen korrigiert ist. Zeige ich aber alles im Video (rendert gerade).

**Comment by kreuvf** [comment]
Link zum Video: https://www.youtube.com/watch?v=5sOdcxNbn2s
