### ISSUE TITLE
Missing GM sheet rolls

### ISSUE THREAD

**Issue by YuanRamirez** [kreuvf/roll20-character-sheets#7]
Please add hidden GM-rolls to the abilities (Talente)

**Comment by kreuvf** [comment]
(If I should write in English, please say so.)

Was genau verstehst du unter versteckte Meisterwürfe?
* Meister kann würfeln, ohne dass die anderen es sehen
* Spieler würfelt, aber nur der Meister kann das Ergebnis sehen

**Comment by YuanRamirez** [comment]
Naja, an sich meine ich beides. Bei den Gaben wie zum Beispiel Gefahreninstinkt, funktioniert das schon soweit. Da gibt es einen Knopf, der dann anstatt den Würfelwurf in den öffentlichen Chat zu schreiben, den GM anflüstert.
Da sowohl GM als auch der kontrollierende Spieler Zugriff auf den Charakterbogen haben, können mit so einem Knopf die Spieler einen Würfelwurf machen, den nur der Spielleiter sehen kann), UND der Spielleiter kann eine Probe würfeln, deren Ergebnis niemand außer ihm sieht. Beides ist im Spielverlauf hilfreich.
Ich würfel immer gerne sowas wie Sinnesschärfe komplett verdeckt (d.h. ohne, dass die Spieler wissen, dass es überhaupt eine Probe gibt), damit die Spieler nicht anfangen Ansagen zu machen wie: "Oh, ich hab die Sinnesschärfe-Probe nicht geschafft, um die du mich gebeten hast. Ich.. ähm... schau mich nochmal genau um.... oder... hör nochmal genau hin...? Kann ich die Probe wiederholen?"
Das mache ich natürlich nicht, wenn der Spieler explizit seine Ohren an eine Tür drückt und irgendwen belauschen will, sondern wenn ich schauen möchte, ob die Spieler den sich anschleichenden Meuchelmörder hören etc..

**Comment by kreuvf** [comment]
Jetzt, wo du es erklärt hast, leuchtet mir ein, dass meine Nachfrage unsinnig war ;D Steht auf der Todo-Liste.

**Comment by kreuvf** [comment]
Dieses Thema sollte automatisch geschlossen werden, wenn der Pull Request #2889 angenommen wird. Danke für euer Feedback ^.^

**Comment by kreuvf** [comment]
[Video](https://www.youtube.com/watch?v=l2SCwz51T9g) geht morgen gegen 17 Uhr live, da gibt es dann schon mal eine Preview der Änderungen.
