### ISSUE TITLE
No attribute was found for @{Jucho Stipkow|FK_Aktiv}/ Fernangriff funktioniert nicht.

### ISSUE THREAD

**Issue by Sokratess** [kreuvf/roll20-character-sheets#71]
Habe versucht einen Fernkampfangriff zu würfeln. Attribute fehlt. 
![2021-04-17 19 32 24 app roll20 net 71646e7a70f5](https://user-images.githubusercontent.com/82724440/115121556-a91acb80-9fb3-11eb-85a2-c99910ce042f.jpg)

**Comment by kreuvf** [comment]
Es sollte reichen einmal die FK-Waffe zu wechseln oder aus- und wieder anzuschalten, dann sollte sich das wieder einrenken :)

**Comment by kreuvf** [comment]
Dieser Fehler könnte mit dem aktuellen Pull Request (#9488) automatisch mitbehoben worden sein. Ich poste hier nochmal, wenn die neue Version online ist und bitte dann um Info, ob dieses Problem weiterhin auftaucht.

**Comment by kreuvf** [comment]
Die neue Version wird voraussichtlich ab morgen gegen 18:00 Uhr online gehen. Ich bitte daher um Rückmeldung, sodass dieses Issue hier geschlossen werden kann, wenn der Fehler nicht mehr auftritt. :partying_face:

**Comment by kreuvf** [comment]
@Sokratess Besteht der Bug weiterhin?

**Comment by kreuvf** [comment]
@Sokratess Letzte Nachfrage, bevor ich das Issue als erledigt markiere und schließe: Kannst du den Fehler noch reproduzieren? BItte antworte bis Samstag, den 8. Januar 2022.

**Comment by kreuvf** [comment]
Nicht (mehr) reproduzierbar.
