### ISSUE TITLE
Neuer Charakter: 'PA_Aktiv' ist 0

### ISSUE THREAD

**Issue by blxydr** [kreuvf/roll20-character-sheets#72]
Ich habe nach dem Update auf Version 20210415 einen neuen Charakter (NSC) angelegt.

Dort habe ich nacheinander diverse Waffen zugeordnet und die Talente eingestellt (Zweihandschwerter, Raufen, Schwerter). Die Attacke wird korrekt berechnet, die Parade ist jedoch dauerhaft bei 0.

NKWAktiv1 = 1
NKW_AT_typ1 = @{AT_Zweihandschwerter}
NKW_PA_typ1 = @{PA_Zweihandschwerter}
PA_Aktiv = 0
AT_zweihandschwerter = 17
PA_zweihandschwerter = 25

**Comment by kreuvf** [comment]
Ich versuche das nachzustellen. Wärst du/Wärt ihr bereit mir zur Feststellung der Ursache auch einen Beitrittslink (per Privatnachricht an "Isurandil" auf Roll20) zum entsprechenden Spiel zu geben und mir die Kontrolle über den Charakter zu geben?

**Comment by kreuvf** [comment]
Ich habe die Wurzel des Übels ausfindig machen können: Neue Charaktere hatten noch nie Wunden, daher ist der entsprechende Wert für den Einfluss der Wunden auf die Parade nicht gesetzt.

Die Lösung des Problem ist aber denkbar einfach:
* Beliebige Wunde an- und wieder abhaken.

Da es für diesen Fehler eine einfache Abhilfe gibt, bleibt der Fehler vorerst noch offen.

Danke fürs Melden! :heart:

**Comment by blxydr** [comment]
Super, danke! Dieser Workaround funktioniert tatsächlich einwandfrei :-)
