### ISSUE TITLE
Sonderfertigkeit Rüstungsgewöhnung III: falsche INI-Berechnung

### ISSUE THREAD

**Issue by blxydr** [kreuvf/roll20-character-sheets#74]
Hat ein Charakter die o.g. SF, so sollte der INI-Malus nur noch BE/2 betragen. Im Charakterbogen wird aber anscheinend weiterhin die BE abgezogen.

**Comment by kreuvf** [comment]
Vielen Dank fürs Melden! Ist tatsächlich falsch, habe ich nicht auf dem Schirm gehabt. :+1:

**Comment by kreuvf** [comment]
Die dazugehörige Regelstelle ist Wege des Schwerts, S. 76. Wichtig: Der INI-Malus betrifft nur Behinderung aus der Rüstung:
> [...] der wird von jeglicher Form von Rüstung um 2 Punkte weniger behindert [...] und muss außerdem nur die Hälfte INI-Abzüge der Rüstung hinnehmen, also (BE–2)/2.

Das bedeutet, dass Behinderung aus Last weiterhin voll angezählt wird.

**Comment by blxydr** [comment]
Ja, genau. Stand nicht infrage

Am 11.07.2021 16:52 schrieb Kreuvf:

**Comment by kreuvf** [comment]
Das war mehr eine kleine Erinnerung an mich, wenn ich das Problem angehe ^.^ Möglicherweise geschieht dies sehr bald ;)

**Comment by blxydr** [comment]
Ah, alles klar :-) Dann viel Erfolg :)

Am 11.07.2021 20:30 schrieb Kreuvf:

**Comment by kreuvf** [comment]
So, das ist dann in der Entwicklerversion auch so gut wie behoben ... :)

**Comment by blxydr** [comment]
Super! :-) Danke

Am 18.07.2021 21:33 schrieb Kreuvf:
