### ISSUE TITLE
AT/PA/Schild

### ISSUE THREAD

**Issue by Mardugh** [kreuvf/roll20-character-sheets#75]
Mahlzeit, mein Problem kurz zusammengefasst.

Es gibt keinen Button mehr für "Schildparade". Zudem gibt es seit dem letzten UPDate auch noch das Problem, dass sich meine Kampfwerte nach Auswahl einer neuen Waffe erst anpassen wenn ich den Schild einmal ab- und wieder angewählt habe.

**Comment by kreuvf** [comment]
Hilft es, wenn du einmal eine Wunde an- und wieder abschaltest?

**Comment by Mardugh** [comment]
Nein, das hatte ich schon im forum gelesen und probiert.. die schildparade ist gänzlich weg, aber die Attacke ist da. Es wirkt sich wie gesagt nur auf die Attacke und paradewerte aus. Was ich durch deaktivieren und aktivieren des Schildes wieder ändern kann.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.05.21, 06:34 schrieb Kreuvf ***@***.***>:

   
  Hilft es, wenn du einmal eine Wunde an- und wieder abschaltest?

**Comment by kreuvf** [comment]
Am schnellsten sollte es gehen, wenn du mir, am besten via Mail (webmaster@<nickname>.de) den Beitrittslink zu eurem Spiel schickst und euer Meister mir Zugriff auf deinen Charakter gibt. Muss natürlich nicht sein, wenn ihr das nicht wollt. Ich finde dann schon einen anderen Weg :)

**Comment by Mardugh** [comment]
Ich guck das ich das morgen geregelt bekomme, heute bin ich unterwegs-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.05.21, 08:16 schrieb Kreuvf ***@***.***>:

   
  Am schnellsten sollte es gehen, wenn du mir, am besten via Mail ***@***.***) den Beitrittslink zu eurem Spiel schickst und euer Meister mir Zugriff auf deinen Charakter gibt. Muss natürlich nicht sein, wenn ihr das nicht wollt. Ich finde dann schon einen anderen Weg :)

**Comment by kreuvf** [comment]
Kein Problem. Du kannst auch an den Account "Isurandil" auf Roll20 den Link schicken, dann geht das auch ohne, dass ich (d)eine E-Mail-Adresse kenne. :)

**Comment by Mardugh** [comment]
https://app.roll20.net/join/6217357/RxBldg

 

kommst du damit klar ? Mein meister weiss gerade nicht wies ingame geht und die freigabe muss er dir dann morgen abend geben wenn das klappt

 

 
 

Gesendet: Dienstag, 18. Mai 2021 um 18:13 Uhr
Von: "Kreuvf" ***@***.***>
An: "kreuvf/roll20-character-sheets" ***@***.***>
Cc: "Mardugh" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [kreuvf/roll20-character-sheets] AT/PA/Schild (#75)


 

Kein Problem. Du kannst auch an den Account "Isurandil" auf Roll20 den Link schicken, dann geht das auch ohne, dass ich (d)eine E-Mail-Adresse kenne. :)

**Comment by kreuvf** [comment]
> https://app.roll20.net/join/ZENSIERT   kommst du damit klar ? Mein meister weiss gerade nicht wies ingame geht und die freigabe muss er dir dann morgen abend geben wenn das klappt

Ja, ich komme damit klar, aber den Beitrittslink öffentlich zu posten, bedeutet, dass jeder beitreten kann ;) Ich habe das mal entfernt, ihn mir aber gesichert, damit ihr nicht ungebetenen Besuch erhaltet :)

**Comment by kreuvf** [comment]
Ich habe gerade gemerkt, dass das der falsche Link ist. Wenn der Meister dem Spiel beitritt, erscheint im Chat ein versteckter Link (mit der Maus darüberfahren, damit er sichtbar wird). Das ist der Beitrittslink, mit dem andere Spieler beitreten können und den ich benötige.

**Comment by kreuvf** [comment]
Euer Meister braucht auch nichts zu machen, es reicht mir, wenn ich Zugriff auf das Spiel habe, dann sollte ich mir den Charakter herauskopieren können. Wenn ich das Problem dann gelöst habe, schreibe ich dir (Roll20 und/oder hier).

**Comment by kreuvf** [comment]
Hinweis: Wenn du auf die E-Mails von Github antwortest, landen die Antworten automatisch im Issue und sind öffentlich.

**Comment by Mardugh** [comment]
Oh okay das war mir nicht bewusst, wie ist dann deine Mail genau?-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 19.05.21, 07:47 schrieb Kreuvf ***@***.***>:

   
  Hinweis: Wenn du auf die E-Mails von Github antwortest, landen die Antworten automatisch im Issue und sind öffentlich.

**Comment by Mardugh** [comment]
Wir gucken mal ob wir das irgendwie in den griff bekommen, aber wenns nach mir ginge könnte man auch kurz telefonieren anstatt tausende von textnachrichten hin und her zu schicken ;)

 

 
 

Gesendet: Mittwoch, 19. Mai 2021 um 07:47 Uhr
Von: "Kreuvf" ***@***.***>
An: "kreuvf/roll20-character-sheets" ***@***.***>
Cc: "Mardugh" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [kreuvf/roll20-character-sheets] AT/PA/Schild (#75)


 

Hinweis: Wenn du auf die E-Mails von Github antwortest, landen die Antworten automatisch im Issue und sind öffentlich.

**Comment by Mardugh** [comment]
Achso du hattest mit eine mailadresse geschickt, aber fehlt da nicht was ?
***@***.***)
 

 
 

Gesendet: Mittwoch, 19. Mai 2021 um 07:47 Uhr
Von: "Kreuvf" ***@***.***>
An: "kreuvf/roll20-character-sheets" ***@***.***>
Cc: "Mardugh" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [kreuvf/roll20-character-sheets] AT/PA/Schild (#75)


 

Hinweis: Wenn du auf die E-Mails von Github antwortest, landen die Antworten automatisch im Issue und sind öffentlich.

**Comment by Mardugh** [comment]
Um das ganze zu beschleunigen... Kann ich meine char exportieren und in einem neu von mir aufgemachtem Spiel einfügen ?

 
 

Gesendet: Mittwoch, 19. Mai 2021 um 07:47 Uhr
Von: "Kreuvf" ***@***.***>
An: "kreuvf/roll20-character-sheets" ***@***.***>
Cc: "Mardugh" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [kreuvf/roll20-character-sheets] AT/PA/Schild (#75)


 

Hinweis: Wenn du auf die E-Mails von Github antwortest, landen die Antworten automatisch im Issue und sind öffentlich.

**Comment by Mardugh** [comment]
Ah sehr gut char ist drin-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 19.05.21, 18:29 schrieb Kreuvf ***@***.***>:

   
   
   Um das ganze zu beschleunigen... Kann ich meine char exportieren und in einem neu von mir aufgemachtem Spiel einfügen ? 
   
  Ja, das sollte funktionieren. 
   
   Trete diesem Spiel bei: https://app.roll20.net/join/10694333/ZzYAAg 
   Tools -> Character Vault (Deutsch: Digitale Werkzeuge -> Charaktertresor) 
   Importiere vorhandenen Charakter (suche das Spiel und den Charakter aus, den du in den Character Vault importieren möchtest) 
   Dann siehst du den Charakter im Character Vault und hast die Möglichkeit ein Spiel auszuwählen. 
   Wähle "Isus Hilfespiel" aus und exportiere den Charakter dann in das Spiel 
   
  Alles Weitere mache dann ich und melde mich, wenn ich weiß, was das Problem behebt :)

**Comment by kreuvf** [comment]
Wenn Roll20 da nicht irgendeinen Käse gemacht hat, dann liegt das Problem daran, dass du keinen Schild unter Kampf -> Ausrüstung hinzugefügt und aktiviert hast. Nahkampfwaffe war auch keine aktiv.

Zwei Einträge für "Waffe mit Schild" und "Waffe" sollten seit den letzten Änderungen nicht mehr nötig sein. Schildangriff kannst du ohne Schildkampf I nicht ausführen und wird dir daher nicht angezeigt.

Vermutlich ohne Relevanz, aber ich habe auch einmal den Bogen-TaW geändert und zurückgeändert, damit die Berechnungen der FK-Werte durchgeführt werden.

Du kannst im Hilfespiel in den Charakter gucken, was ich eingestellt habe und solltest dann in eurem Spiel bei den Häkchen an der gleichen Stelle das gleiche Ergebnis bekommen :)

**Comment by kreuvf** [comment]
Problem behoben: Wert für TP/KK war "0" und hat in Konsequenz zu einem Abbruch der Berechnungen geführt.
