### ISSUE TITLE
Trefferpunkte Wurf resultiert in 0 TP 

### ISSUE THREAD

**Issue by renkash** [kreuvf/roll20-character-sheets#80]
Wenn man durch Wuchtschläge/Ansagen Bonusschaden an der Funktion "Trefferpunkte" zurechnen möchte,
resultiert dies in einem 0 TP Wurf. 

Aber nur wenn man ein + vor den Bonusschadenwert setzt. (Soweit ich das sehen kann in der Rechnung fehlt da eine Klammer)

Lässt man das + weg ist alles in Ordnung.

Das ist soweit ich das sehen kann überall so, ob Nah-, Fern- oder Schildtreffer.
![Fernkampftreffer0](https://user-images.githubusercontent.com/84713575/119400650-c2154b80-bcda-11eb-92d1-4611bc953fde.PNG)

![Nahkampftreffer0](https://user-images.githubusercontent.com/84713575/119401005-3223d180-bcdb-11eb-9e58-48e2790184d1.PNG)

![TPBonusPlus4](https://user-images.githubusercontent.com/84713575/119401015-35b75880-bcdb-11eb-9f77-a582901b62c6.PNG)

Rechnung wenn man stattdessen "4" eingibt.

![TPBonusKalkulationJust4](https://user-images.githubusercontent.com/84713575/119401370-b24a3700-bcdb-11eb-951f-98cf2f927a25.png)

**Comment by kreuvf** [comment]
Das hast du ganz richtig erkannt: Diese Formel habe ich noch nicht robust gemacht, indem eine Klammer um den TP-Bonus/Malus eingefügt wird. Danke für's Melden :)

**Comment by renkash** [comment]
Yes!! 
War mir nicht 100% sicher. Die Formate von Roll20 sind leider noch bissl Böhmische Dörfer für mich.
