### ISSUE TITLE
initiative berechnung schlägt fehl

### ISSUE THREAD

**Issue by Garonenur** [kreuvf/roll20-character-sheets#90]
der Button für die Initiative löst (dreifach) folgende Meldung im Chat aus:
`No attribute was found for @{Valperto Kalamal|BE_RG_INI}`
es wird nach einem Modifikator gefragt, aber es erscheint keine Initiative.

**Comment by Garonenur** [comment]
FIX (Workaround):
einmal die Rüstungsgewöhnung abschalten und wieder aktivieren. Danach ist das Attribut auch vorhanden.

**Comment by kreuvf** [comment]
Dass die Meldung dreimal erscheint, liegt daran, dass das Attribut `BE_RG_INI` dreimal im Buttoncode auftaucht:

> @{gm_roll_opt} &{template:DSA-Initiative} {{char=@{Name}}} {{mod=[[?{Bonus (+) oder Malus (−)|0}d1cs0cf2]]}} {{dice=[[@{INI_dice_count}]]}} {{IB=[[@{INIBasis2}]]}} {{BE=[[(@{BE_Last}) + (**@{BE_RG_INI}**)]]}} {{BE_Last=[[@{BE_Last}]]}} {{BE_RG_INI=[[**@{BE_RG_INI}**]]}} {{rg3=[[@{sf_rustungsgewohnungIII}]]}} {{ini=[[(@{INI_dice_count}d6 + @{INIBasis2} - (@{BE_Last}) - (**@{BE_RG_INI}**) + ([[@{INI_mod_hauptwaffe}]]) + ([[@{ShieldParryINI}]]) + [[?{Bonus (+) oder Malus (−)|0}d1cs0cf2]])&{tracker}]]}}

Die eigentliche Ursache ist, dass Attribute, die nur von Sheetworker Scripts gesetzt werden, nicht im Charakterbogen verfügbar sind, bis sie eben das erste Mal gesetzt wurden. Dahinter steckt also eine ganze Fehlerklasse, die sich durch eine Initialisierung ausschalten lassen sollte. Ich habe mal ein entsprechendes Issue (#91) aufgemacht.
