### ISSUE TITLE
Spezialisierungen bei 3W20-Wurf falsch berechnet

### ISSUE THREAD

**Issue by bb-froggy** [kreuvf/roll20-character-sheets#93]
Hallo,

erstmal, das Char Sheet für DSA 4.1 ist wirklich toll :-).

Bei den Spezialisierungen wird der Talentwurf bei Erschwernissen > TaW-2 falsch berechnet, weil die +2 bei jedem Wurf zu den verbrauchten TaP hinzuaddiert werden statt abgezogen. Hier mal ein Beispiel, an dem man den Fehler sieht:
![image](https://user-images.githubusercontent.com/587120/145278240-b8888d5c-f42c-45f1-a079-ce8dab133beb.png)
Hier wird auf 13/8/8 bei TaW 0 (+Spezialisierung) gewürfelt, die Würfel zeigen 15/8/5. Das wäre genau geschafft, die zwei TaP aus der Spezialisierung wären beim ersten Wurf verbraucht worden, stattdessen sagt das Sheet, dass es mit -4 TaP* misslungen ist. Natürlich wäre bei TaW 0 gar keine Spezialisierung möglich, aber das Problem entsteht genauso bei TaW 7 und einer Erschwernis von 7.

Als Beispiel, hier mal der aktualisierte Code für Fliegen (für die Änderungen für einen ganzen Pull Request habe ich gerade keine Zeit, vielleicht ein andermal):

                    <button name="FliegenSpez" type="roll" value="@{gm_roll_opt} &{template:DSA-Talente} {{name=Fliegen (@{spez_fliegen})}} {{mod=[[?{Erleichterung (−) oder Erschwernis (+)|0}d1cs0cf2]]}} {{taw=[[@{TaW_fliegen} + 2]]}} {{stat1=[[@{Eigenschaft1fliegen}]]}} {{stat2=[[@{Eigenschaft2fliegen}]]}} {{stat3=[[@{Eigenschaft3fliegen}]]}} {{Talent=[[ { [[{0d1 + @{TaW_fliegen} + 2 - (?{Erleichterung (−) oder Erschwernis (+)|0}), 0d1}kh1]] - {1d20cs1cf20 + [[{0d1 + (?{Erleichterung (−) oder Erschwernis (+)|0}) - @{TaW_fliegen} - 2, 0d1}kh1]] - @{Eigenschaft1fliegen}, 0d1}kh1 - {1d20cs1cf20 + [[{0d1 + (?{Erleichterung (−) oder Erschwernis (+)|0}) - @{TaW_fliegen} - 2, 0d1}kh1]] - @{Eigenschaft2fliegen}, 0d1}kh1 - {1d20cs1cf20 + [[{0d1 + (?{Erleichterung (−) oder Erschwernis (+)|0}) - @{TaW_fliegen} - 2, 0d1}kh1]] - @{Eigenschaft3fliegen}, 0d1}kh1, 0d1 + @{TaW_fliegen} + 2}dh1]]}}">Spez</button>

**Comment by kreuvf** [comment]
Ich schaue es mir morgen mal in Ruhe an. Das wird aber hoffentlich ohnehin bald™ unnötig, wenn die Würfe über Custom Roll Parsing abgehandelt werden.

**Comment by kreuvf** [comment]
Ich kann das Problem bestätigen.

**Comment by kreuvf** [comment]
Zauber ebenfalls betroffen.

**Comment by kreuvf** [comment]
So, habe dem Bug mal etwas hinterherrecherchiert und der ist durch Commit 44132a41c4b427f39944c3645dae1440de0b41ba vom 24. Februar 2016 ins Sheet gekommen, also quasi seit Anbeginn des Charakterbogens dabei.
